.TH "ggzduedit" "6" "0.0.5" "The GGZ Development Team" "GGZ Gaming Zone"
.SH "NAME"
.LP 
ggzduedit \- User management tool for the GGZ Gaming Zone server
.SH "DESCRIPTION"
.LP
This tools allows you to view the list of currently registered users,
as well as add new ones or delete some registrations.
.SH "FILES"
.LP 
\fI/usr/var/ggzd/player.db\fP - player registry
.SH "AUTHORS"
.LP 
The GGZ Development Team
<ggz\-dev@lists.sourceforge.net>
