.TH "ggzd" "6" "0.0.4" "The GGZ Development Team" "GGZ Gaming Zone"
.SH "NAME"
.LP 
ggzd \- GGZ Gaming Zone Main Server
.SH "DESCRIPTION"
.LP
The server ggzd is a multi-process daemon which forks a child
server for every launched game. It listens on port 5688 for
incoming connections from GGZ core clients (or other clients
like the chatbot grubby).
.SH "FILES"
.LP 
\fI/etc/ggzd/ggzd.motd\fP - message of the day
.LP
\fI/etc/ggzd/ggzd.conf\fP - configuration
.SH "AUTHORS"
.LP 
The GGZ Development Team
<ggz\-dev@lists.sourceforge.net>
