.TH "ggzduedit" "6" "0.0.8" "The GGZ Development Team" "GGZ Gaming Zone"
.SH "NAME"
.LP 
ggzduedit \- User management tool for the GGZ Gaming Zone server
.SH "SYNOPSIS"
.LP
.B ggzduedit
[\fIDATADIR\fR]
.SH "DESCRIPTION"
.LP
This tools allows you to view the list of currently registered users,
as well as add new ones or delete some registrations.
In case there are multiple ggzd installations around, an alternative data
directory may be passed to ggzduedit as an option.
.SH "FILES"
.LP 
\fI/var/ggzd/player.db\fP - player registry
.SH "AUTHORS"
.LP 
The GGZ Development Team
<ggz\-dev@mail.ggzgamingzone.org>
