#! /usr/bin/env python
# encoding: utf-8
# Copyright (C) 2007 Josef Spillner <josef@ggzgamingzone.org>

VERSION='0.0.14+'
APPNAME='libggz'

srcdir = '.'
blddir = 'build'

def set_options(opt):
	opt.tool_options('compiler_cc')

def configure(conf):
	conf.check_tool('compiler_cc')

def build(bld):
	bld.add_subdirs('src')
	bld.add_subdirs('tests')

