files = safestring flexprintf str evilstr

CC = gcc
CPPFLAGS = -I /home/ggznew/BUILD/include/
CFLAGS = -Wall -Werror -O2 -std=gnu99
LDFLAGS = -L /home/ggznew/BUILD/lib/
LDLIBS = -lggz

all: $(files)

clean:
	rm -f $(files)

