COMBAT_VERSION=1.2

COMBAT_PROTOCOL_ENGINE=Combat
COMBAT_PROTOCOL_VERSION=3

AC_SUBST(COMBAT_VERSION)
AC_SUBST(COMBAT_PROTOCOL_ENGINE)
AC_SUBST(COMBAT_PROTOCOL_VERSION)

AC_DEFINE_UNQUOTED([COMBAT_VERSION], "$COMBAT_VERSION", [Combat version])
AC_DEFINE_UNQUOTED([COMBAT_PROTOCOL_ENGINE], "$COMBAT_PROTOCOL_ENGINE",
		   [Combat protocol engine])
AC_DEFINE_UNQUOTED([COMBAT_PROTOCOL_VERSION], "$COMBAT_PROTOCOL_VERSION",
		   [Combat protocol version])
