/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "prefs_cb.h"
#include "prefs_dlg.h"
#include "support.h"

GtkWidget*
create_dlg_prefs (void)
{
  GtkWidget *dlg_prefs;
  GtkWidget *dialog_vbox1;
  GtkWidget *vbox1;
  GtkWidget *frame1;
  GtkWidget *check_beep;
  GtkWidget *frame2;
  GtkWidget *hbox1;
  GtkWidget *dir_entry;
  GtkWidget *vbuttonbox1;
  GtkWidget *browse_button;
  GtkWidget *default_button;
  GtkWidget *dialog_action_area1;
  GtkWidget *ok_button;
  GtkWidget *apply_button;
  GtkWidget *cancel_button;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  dlg_prefs = gtk_dialog_new ();
  gtk_widget_set_name (dlg_prefs, "dlg_prefs");
  gtk_object_set_data (GTK_OBJECT (dlg_prefs), "dlg_prefs", dlg_prefs);
  gtk_window_set_title (GTK_WINDOW (dlg_prefs), "Chinese Checkers Preferences");
  gtk_window_set_policy (GTK_WINDOW (dlg_prefs), TRUE, TRUE, FALSE);

  dialog_vbox1 = GTK_DIALOG (dlg_prefs)->vbox;
  gtk_widget_set_name (dialog_vbox1, "dialog_vbox1");
  gtk_object_set_data (GTK_OBJECT (dlg_prefs), "dialog_vbox1", dialog_vbox1);
  gtk_widget_show (dialog_vbox1);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (dlg_prefs), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), vbox1, TRUE, TRUE, 0);

  frame1 = gtk_frame_new ("General Preferences");
  gtk_widget_set_name (frame1, "frame1");
  gtk_widget_ref (frame1);
  gtk_object_set_data_full (GTK_OBJECT (dlg_prefs), "frame1", frame1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox1), frame1, FALSE, FALSE, 0);

  check_beep = gtk_check_button_new_with_label ("Beep on our turn");
  gtk_widget_set_name (check_beep, "check_beep");
  gtk_widget_ref (check_beep);
  gtk_object_set_data_full (GTK_OBJECT (dlg_prefs), "check_beep", check_beep,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (check_beep);
  gtk_container_add (GTK_CONTAINER (frame1), check_beep);
  gtk_container_set_border_width (GTK_CONTAINER (check_beep), 2);

  frame2 = gtk_frame_new ("Board Theme Directory");
  gtk_widget_set_name (frame2, "frame2");
  gtk_widget_ref (frame2);
  gtk_object_set_data_full (GTK_OBJECT (dlg_prefs), "frame2", frame2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (vbox1), frame2, TRUE, TRUE, 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox1, "hbox1");
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (dlg_prefs), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (frame2), hbox1);

  dir_entry = gtk_entry_new ();
  gtk_widget_set_name (dir_entry, "dir_entry");
  gtk_widget_ref (dir_entry);
  gtk_object_set_data_full (GTK_OBJECT (dlg_prefs), "dir_entry", dir_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (dir_entry);
  gtk_box_pack_start (GTK_BOX (hbox1), dir_entry, TRUE, TRUE, 0);
  gtk_widget_set_usize (dir_entry, 225, -2);
  gtk_tooltips_set_tip (tooltips, dir_entry, "Enter a directory pathname which contains a Chinese Checkers theme graphics set", NULL);
  gtk_entry_set_text (GTK_ENTRY (dir_entry), "/usr/local/lib/ggz/ccheckers/pixmaps/default");

  vbuttonbox1 = gtk_vbutton_box_new ();
  gtk_widget_set_name (vbuttonbox1, "vbuttonbox1");
  gtk_widget_ref (vbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (dlg_prefs), "vbuttonbox1", vbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbuttonbox1);
  gtk_box_pack_start (GTK_BOX (hbox1), vbuttonbox1, TRUE, TRUE, 0);

  browse_button = gtk_button_new_with_label ("Browse");
  gtk_widget_set_name (browse_button, "browse_button");
  gtk_widget_ref (browse_button);
  gtk_object_set_data_full (GTK_OBJECT (dlg_prefs), "browse_button", browse_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (browse_button);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), browse_button);
  GTK_WIDGET_SET_FLAGS (browse_button, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, browse_button, "Open a directory browser to locate a theme directory", NULL);

  default_button = gtk_button_new_with_label ("Default");
  gtk_widget_set_name (default_button, "default_button");
  gtk_widget_ref (default_button);
  gtk_object_set_data_full (GTK_OBJECT (dlg_prefs), "default_button", default_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (default_button);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), default_button);
  GTK_WIDGET_SET_FLAGS (default_button, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, default_button, "Click to reset default theme graphics", NULL);

  dialog_action_area1 = GTK_DIALOG (dlg_prefs)->action_area;
  gtk_widget_set_name (dialog_action_area1, "dialog_action_area1");
  gtk_object_set_data (GTK_OBJECT (dlg_prefs), "dialog_action_area1", dialog_action_area1);
  gtk_widget_show (dialog_action_area1);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area1), 10);

  ok_button = gtk_button_new_with_label ("OK");
  gtk_widget_set_name (ok_button, "ok_button");
  gtk_widget_ref (ok_button);
  gtk_object_set_data_full (GTK_OBJECT (dlg_prefs), "ok_button", ok_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ok_button);
  gtk_box_pack_start (GTK_BOX (dialog_action_area1), ok_button, FALSE, FALSE, 0);
  gtk_widget_set_usize (ok_button, 48, -2);
  gtk_tooltips_set_tip (tooltips, ok_button, "Save changes and dismiss preferences dialog", NULL);

  apply_button = gtk_button_new_with_label ("Apply");
  gtk_widget_set_name (apply_button, "apply_button");
  gtk_widget_ref (apply_button);
  gtk_object_set_data_full (GTK_OBJECT (dlg_prefs), "apply_button", apply_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (apply_button);
  gtk_box_pack_start (GTK_BOX (dialog_action_area1), apply_button, FALSE, FALSE, 0);
  gtk_widget_set_usize (apply_button, 48, -2);
  gtk_tooltips_set_tip (tooltips, apply_button, "Save changes, keeping preferences dialog open", NULL);

  cancel_button = gtk_button_new_with_label ("Cancel");
  gtk_widget_set_name (cancel_button, "cancel_button");
  gtk_widget_ref (cancel_button);
  gtk_object_set_data_full (GTK_OBJECT (dlg_prefs), "cancel_button", cancel_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cancel_button);
  gtk_box_pack_start (GTK_BOX (dialog_action_area1), cancel_button, FALSE, FALSE, 0);
  gtk_widget_set_usize (cancel_button, 48, -2);
  gtk_tooltips_set_tip (tooltips, cancel_button, "Cancel changes since the last apply", NULL);

  gtk_signal_connect (GTK_OBJECT (browse_button), "clicked",
                      GTK_SIGNAL_FUNC (on_browse_button_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (default_button), "clicked",
                      GTK_SIGNAL_FUNC (on_default_button_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (ok_button), "clicked",
                      GTK_SIGNAL_FUNC (on_ok_button_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (apply_button), "clicked",
                      GTK_SIGNAL_FUNC (on_apply_button_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (cancel_button), "clicked",
                      GTK_SIGNAL_FUNC (on_cancel_button_clicked),
                      NULL);

  gtk_object_set_data (GTK_OBJECT (dlg_prefs), "tooltips", tooltips);

  return dlg_prefs;
}

