#!/usr/bin/env python

import pg

cns = pg.DB(host="localhost", dbname="ggz", user="ggzd", passwd="bahouh")

q = cns.query("SELECT handle, longitude, latitude, handle FROM userinfo WHERE latitude IS NOT NULL")

def norm((longitude, latitude), weight):
	mapwidth = 596
	mapheight = 331
	longnorm = longitude + 180
	latnorm = latitude + 90
	calibrate_x = -10
	calibrate_y = -20
	xpos = int((longnorm + calibrate_x) * mapwidth / 360)
	ypos = int((latnorm + calibrate_y) * mapheight / 180)
	xpos -= int(weight / 2)
	ypos -= int(weight / 2)
	return (xpos, ypos)

print "<map name='ggzmap'>"

for row in q.dictresult():
	longitude = int(row['longitude'])
	latitude = int(row['latitude'])
	handle = row['handle']
	#print longitude, latitude, 10
	(x, y) = norm((longitude, latitude), 10)
	#print "norm", x, y
	x = x / 4
	y = 83 - y / 4
	coords = str(x) + "," + str(y) + "," + str(x + 10) + "," + str(y + 10)
	coords = "coords='" + coords + "'"
	alt = "alt='" + handle + "'"
	title = "title='" + handle + "'"
	href = "href='/db/players/?lookup=" + handle + "'"
	print "<area " + coords + " " + alt + " " + title + " " + href + ">"
print "</map>"

