#!/usr/bin/env python

import pg

cns = pg.DB(host="XXX", dbname="XXX", user="XXX", passwd="XXX")

q = cns.query("SELECT longitude, latitude, handle FROM userinfo WHERE latitude IS NOT NULL")

for row in q.dictresult():
	longitude = int(row['longitude'])
	latitude = int(row['latitude'])
	handle = row['handle']
	print longitude, latitude, 8

