CHESS_VERSION=0.0.8

CHESS_PROTOCOL_ENGINE=Chess
CHESS_PROTOCOL_VERSION=3

AC_SUBST(CHESS_VERSION)
AC_SUBST(CHESS_PROTOCOL_ENGINE)
AC_SUBST(CHESS_PROTOCOL_VERSION)

AC_DEFINE_UNQUOTED([CHESS_VERSION], "$CHESS_VERSION", [Chess version])
AC_DEFINE_UNQUOTED([CHESS_PROTOCOL_ENGINE], "$CHESS_PROTOCOL_ENGINE",
		   [Chess protocol engine])
AC_DEFINE_UNQUOTED([CHESS_PROTOCOL_VERSION], "$CHESS_PROTOCOL_VERSION",
		   [Chess protocol version])
