#!/bin/sh

# das Spiel arbeitet mit wavs, dieses Script dekodiert die mp3 in data/sounds
cd data/sounds
mkdir -p backup
for file in *.mp3
do
	nfile=`basename $file mp3`wav
	mpg123 -w $nfile $file
	mv $file backup
done
