.TH "grubby" "6" "0.0.7" "The GGZ Development Team" "GGZ Gaming Zone"
.SH "NAME"
.LP
grubby \- very intelligent GGZ chat bot
.SH "SYNOPSIS"
.B grubby
[\fIOPTIONS\fR]
.SH "DESCRIPTION"
.LP
Grubby is a modular chat bot, which means this program behaves like a human.
Once logged into a GGZ server, you can tell it some news it shall tell
others, and in return it tells you what it has heard of lately.
Additionally, if you say a bad word, it complains about it.
You can even rename grubby to what you want. Common names are
Highlander and Keeper, but you can invent your own ones.
More functionality can be added by plugging in shared libraries, perl scripts,
ruby gems, and whatnot.
.SH "OPTIONS"
.TP
\fB-h\fR, \fB--help\fR
Display help menu
.TP
\fB-H\fR, \fB--host\fR=hostname
Host to connect to
.TP
\fB-d\fR, \fB--datadir\fR=datadir
Use this directory as data directory
.TP
\fB-n\fR, \fB--name\fR=name
Name with which grubby interacts
.TP
\fB-v\fR, \fB--version\fR
Display grubby version number
.LP
.SH "COMMANDS"
.LP
Grubby accepts both public commands and owner commands. Please view the
appropriate documentation in the ggz-docs module.
.SH "CONFIGURATION"
.LP
Configure grubby using the grubby-config perl script. Except the first two
values (name and owner) all other values can simply be taken from the default
suggestions.
.SH "FILES"
.LP
\fI$HOME/.ggz/grubby.rc\fP - configuration file, may be produced by
grubby-config
.LP
\fI$HOME/.ggz/grubby/*\fP - individual module files and player database
.LP
\fIgrubby-config\fP - user-friendly configuration script
.SH "AUTHORS"
.LP
The GGZ Development Team
<ggz\-dev@lists.sourceforge.net>
