.TH "grubby-config" "6" "0.0.5pre" "The GGZ Development Team" "GGZ Gaming Zone"
.SH "NAME"
.LP 
grubby-config \- Grubby configuration script
.SH "DESCRIPTION"
.LP
Just call grubby-config as the user who will run grubby. It will then ask you
questions, most of them provide a default answer. Only the name and the owner
is necessary information.
.SH "AUTHORS"
.LP 
The GGZ Development Team
<ggz\-dev@lists.sourceforge.net>
