.TH "ggzap" "6" "0.0.12" "The GGZ Development Team" "GGZ Gaming Zone"
.SH "NAME"
.LP 
ggzap \- KDE system tray utily for fast online game launching
.SH "DESCRIPTION"
.LP
GGZap serves as the butler for online game enthusiasts.
It hides into the systray, and if a game is requested it shows
a connection progress window and launches the game appropriately.
It contains a list of games which must be created with ggzmodsniff
first.
.SH "FILES"
.LP 
\fI$HOME/.ggz/ggzap.rc\fP - configuration
.SH "AUTHORS"
.LP 
The GGZ Development Team
<ggz\-dev@mail.ggzgamingzone.org>
.SH "SEE ALSO"
.LP 
kggz(6)
