.TH "ggzmodsniff" "6" "0.0.10" "The GGZ Development Team" "GGZ Gaming Zone"
.SH "NAME"
.LP 
ggzmodsniff \- Sniffer for online game modules
.SH "DESCRIPTION"
.LP
Modsniff, as ggzmodsniff is also called, contacts the GGZ game
module registry (usually /etc/ggz.modules), and compares it with
the games it has already created shortcuts for (usually under
$HOME/.kde/share/applnk/Games/ggz). If there are any updates,
it adds them. During the next months this tool will also be able
to detect external games and add them accordingly. 
.SH "FILES"
.LP 
\fI/etc/ggz.modules\fP - game module registry
.SH "BUGS"
.LP 
None known. Maybe there are difficulties with new frontends or
unusual version numbers.
.SH "AUTHORS"
.LP 
The GGZ Development Team
<ggz\-dev@mail.ggzgamingzone.org>
.SH "SEE ALSO"
.LP 
ggzap(6)
.LP
kggz(6)
