.TH "keepalivecontrol" "6" "0.0.12" "The GGZ Development Team" "GGZ Gaming Zone"
.SH "NAME"
.LP 
keepalivecontrol \- Administration frontend to Keepalive game servers
.SH "DESCRIPTION"
.LP
The Keepalive game server which is part of the GGZ Gaming Zone can
be administered from the outside. Such tasks include creating new worlds,
removing players and general troubleshooting. With the help of
keepalivecontrol, a mouse-driven interface is available for this work.
.SH "BUGS"
.LP 
Keepalive Control is currently not well maintained.
Likewise, the AGS code branch for Keepalive is not enabled by default.
.SH "AUTHORS"
.LP 
The GGZ Development Team
<ggz\-dev@mail.ggzgamingzone.org>
