.TH "kgrubby" "6" "0.0.12" "The GGZ Development Team" "GGZ Gaming Zone"
.SH "NAME"
.LP 
kgrubby \- Graphical configuration tool for the grubby chatbot
.SH "DESCRIPTION"
.LP
The GGZ Gaming Zone chatbot \fBgrubby\fR needs a configuration
before it can be used. It contains its name, owner, default language,
network setup and plugins selection.
Grubby can either be configured using \fBgrubby-config\fR on the
command line, or using \fBkgrubby\fR under KDE.
.LP
Using kgrubby has the advantage of supporting profiles and
offering a compact view on all possible configuration values.
It can also be used to examine the player database and other
aggregate data which has been created while running the bot.
.SH "FILES"
.LP 
\fI$HOME/.ggz/grubby.rc\fP - default grubby configuration
.SH "AUTHORS"
.LP 
The GGZ Development Team
<ggz\-dev@mail.ggzgamingzone.org>
.SH "SEE ALSO"
.LP 
grubby(6), grubby-config(6)
