.TH "shadowbridge" "6" "0.0.7" "The GGZ Development Team" "GGZ Gaming Zone"
.SH "NAME"
.LP
shadowbridge \- Graphical GGZ game network debugging tool
.SH "DESCRIPTION"
.LP
ShadowBridge allows game developers to visualize the network communication
between the game client and the game server.
.LP
It will be launched instead of a game, and will then launch the game itself
under its control. One can even chain thousands of shadow bridges if one has
got enough memory.
.LP
In cases where several frontends are developed for one game, it is possible to
change the \'active\' frontend during the runtime.
.SH "BUGS"
.LP
No known bugs. In the future it should be possible to remember protocols and
\'learn\' about binary opcodes.
.SH "AUTHORS"
.LP
The GGZ Development Team
<ggz\-dev@lists.sourceforge.net>
.SH "SEE ALSO"
.LP
ggzwrap(6)
