/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */


typedef struct {
	int mouse;
	int timeout;
	GtkWidget *menu;
	GtkWidget *item;
	GdkEventMotion *event;
} FakeTips;

void login_set_login (GtkWidget *login);
void login_set_new (GtkWidget *login);
void login_set_chat (GtkWidget *login);
void login_set_chat_rooms(GtkWidget *login);
void login_set_chat_games(GtkWidget *login);
GtkWidget* create_login (void);
