/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <bonobo.h>
#include <gnome.h>

#include "profilesc.h"
#include "profilesi.h"
#include "support.h"


GtkWidget*
create_winProfiles (void)
{
  GtkWidget *winProfiles;
  GtkWidget *hbMain;
  GtkWidget *vbEdit;
  GtkWidget *label5;
  GtkWidget *hbox2;
  GtkWidget *lblProfileName;
  GtkWidget *entProfileName;
  GtkWidget *hbox3;
  GtkWidget *lblUsername;
  GtkWidget *entUsername;
  GtkWidget *hbox4;
  GtkWidget *lblPassword;
  GtkWidget *entPassword;
  GtkWidget *hbox5;
  GtkWidget *lblServer;
  GtkWidget *entServer;
  GtkWidget *hbuttonbox1;
  GtkWidget *btnNew;
  GtkWidget *btnApply;
  GtkWidget *btnDelete;
  GtkWidget *btnDone;
  GtkListStore *stoProfiles;
  GtkWidget *treProfiles;
  GtkCellRenderer *rndProfiles;
  GtkTreeViewColumn *colProfiles;
  GtkTreeSelection *selProfiles;

  winProfiles = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (winProfiles, "winProfiles");
  gtk_widget_set_usize (winProfiles, 600, -2);
  gtk_window_set_title (GTK_WINDOW (winProfiles), _("Advanced Profile Options"));
  gtk_window_set_modal (GTK_WINDOW (winProfiles), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (winProfiles), FALSE);

  hbMain = gtk_hbox_new (FALSE, 5);
  gtk_widget_set_name (hbMain, "hbMain");
  gtk_widget_show (hbMain);
  gtk_container_add (GTK_CONTAINER (winProfiles), hbMain);
  gtk_container_set_border_width (GTK_CONTAINER (hbMain), 4);

  vbEdit = gtk_vbox_new (FALSE, 5);
  gtk_widget_set_name (vbEdit, "vbEdit");
  gtk_widget_show (vbEdit);
  gtk_box_pack_start (GTK_BOX (hbMain), vbEdit, TRUE, TRUE, 0);

  label5 = gtk_label_new (_("This is the advanced profile editor. Select a profile from the right to modify any of it's settings, when done click Apply. To create a new profile, fill out all information and click new."));
  gtk_widget_set_name (label5, "label5");
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (vbEdit), label5, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label5), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label5), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox2, "hbox2");
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbEdit), hbox2, FALSE, TRUE, 0);

  lblProfileName = gtk_label_new (_("Profile Name:"));
  gtk_widget_set_name (lblProfileName, "lblProfileName");
  gtk_widget_show (lblProfileName);
  gtk_box_pack_start (GTK_BOX (hbox2), lblProfileName, FALSE, FALSE, 0);
  gtk_widget_set_usize (lblProfileName, 110, -2);
  gtk_label_set_justify (GTK_LABEL (lblProfileName), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (lblProfileName), 0, 0.5);

  entProfileName = gtk_entry_new ();
  gtk_widget_set_name (entProfileName, "entProfileName");
  gtk_object_set_data_full (GTK_OBJECT (winProfiles), "entProfileName", entProfileName,
                            NULL);
  gtk_widget_show (entProfileName);
  gtk_box_pack_start (GTK_BOX (hbox2), entProfileName, TRUE, TRUE, 0);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox3, "hbox3");
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbEdit), hbox3, FALSE, TRUE, 0);

  lblUsername = gtk_label_new (_("Username:"));
  gtk_widget_set_name (lblUsername, "lblUsername");
  gtk_widget_show (lblUsername);
  gtk_box_pack_start (GTK_BOX (hbox3), lblUsername, FALSE, FALSE, 0);
  gtk_widget_set_usize (lblUsername, 110, -2);
  gtk_label_set_justify (GTK_LABEL (lblUsername), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (lblUsername), 0, 0.5);

  entUsername = gtk_entry_new ();
  gtk_widget_set_name (entUsername, "entUsername");
  gtk_object_set_data_full (GTK_OBJECT (winProfiles), "entUsername", entUsername,
                            NULL);
  gtk_widget_show (entUsername);
  gtk_box_pack_start (GTK_BOX (hbox3), entUsername, TRUE, TRUE, 0);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox4, "hbox4");
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbEdit), hbox4, FALSE, TRUE, 0);

  lblPassword = gtk_label_new (_("Password:"));
  gtk_widget_set_name (lblPassword, "lblPassword");
  gtk_widget_show (lblPassword);
  gtk_box_pack_start (GTK_BOX (hbox4), lblPassword, FALSE, FALSE, 0);
  gtk_widget_set_usize (lblPassword, 110, -2);
  gtk_label_set_justify (GTK_LABEL (lblPassword), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (lblPassword), 0, 0.5);

  entPassword = gtk_entry_new ();
  gtk_widget_set_name (entPassword, "entPassword");
  gtk_object_set_data_full (GTK_OBJECT (winProfiles), "entPassword", entPassword,
                            NULL);
  gtk_widget_show (entPassword);
  gtk_box_pack_start (GTK_BOX (hbox4), entPassword, TRUE, TRUE, 0);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox5, "hbox5");
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbEdit), hbox5, FALSE, TRUE, 0);

  lblServer = gtk_label_new (_("Server:"));
  gtk_widget_set_name (lblServer, "lblServer");
  gtk_widget_show (lblServer);
  gtk_box_pack_start (GTK_BOX (hbox5), lblServer, FALSE, FALSE, 0);
  gtk_widget_set_usize (lblServer, 110, -2);
  gtk_label_set_justify (GTK_LABEL (lblServer), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (lblServer), 0, 0.5);

  entServer = gtk_entry_new ();
  gtk_widget_set_name (entServer, "entServer");
  gtk_object_set_data_full (GTK_OBJECT (winProfiles), "entServer", entServer,
                            NULL);
  gtk_widget_show (entServer);
  gtk_box_pack_start (GTK_BOX (hbox5), entServer, TRUE, TRUE, 0);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox1, "hbuttonbox1");
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbEdit), hbuttonbox1, FALSE, TRUE, 0);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox1), 5);

  btnNew = gtk_button_new_with_mnemonic (_("_New"));
  gtk_widget_set_name (btnNew, "btnNew");
  gtk_widget_show (btnNew);
  gtk_widget_set_sensitive (GTK_WIDGET(btnNew), FALSE);
  gtk_object_set_data_full (GTK_OBJECT (winProfiles), "btnNew", btnNew,
                            NULL);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), btnNew);
  GTK_WIDGET_SET_FLAGS (btnNew, GTK_CAN_DEFAULT);

  btnApply = gtk_button_new_with_mnemonic (_("_Apply"));
  gtk_widget_set_name (btnApply, "btnApply");
  gtk_widget_show (btnApply);
  gtk_widget_set_sensitive (GTK_WIDGET(btnApply), FALSE);
  gtk_object_set_data_full (GTK_OBJECT (winProfiles), "btnApply", btnApply,
                            NULL);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), btnApply);
  GTK_WIDGET_SET_FLAGS (btnApply, GTK_CAN_DEFAULT);

  btnDelete = gtk_button_new_with_mnemonic (_("D_elete"));
  gtk_widget_set_name (btnDelete, "btnDelete");
  gtk_widget_show (btnDelete);
  gtk_widget_set_sensitive (GTK_WIDGET(btnDelete), FALSE);
  gtk_object_set_data_full (GTK_OBJECT (winProfiles), "btnDelete", btnDelete,
                            NULL);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), btnDelete);
  GTK_WIDGET_SET_FLAGS (btnDelete, GTK_CAN_DEFAULT);

  btnDone = gtk_button_new_with_mnemonic (_("_Done"));
  gtk_widget_set_name (btnDone, "btnDone");
  gtk_widget_show (btnDone);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), btnDone);
  GTK_WIDGET_SET_FLAGS (btnDone, GTK_CAN_DEFAULT);

  stoProfiles = gtk_list_store_new (1, G_TYPE_STRING);
  treProfiles = gtk_tree_view_new_with_model (GTK_TREE_MODEL (stoProfiles));
  g_object_unref (G_OBJECT (stoProfiles));
  rndProfiles = gtk_cell_renderer_text_new ();
  g_object_set (G_OBJECT (rndProfiles),
		  "foreground", "black",
		  NULL);
  colProfiles = gtk_tree_view_column_new_with_attributes (_("Profiles"), rndProfiles,
		  "text", 0, NULL);
  gtk_tree_view_append_column (GTK_TREE_VIEW (treProfiles), colProfiles);
  gtk_widget_set_name (treProfiles, "treProfiles");
  gtk_widget_ref (treProfiles);
  gtk_object_set_data_full (GTK_OBJECT (winProfiles), "treProfiles", treProfiles,
                            (GtkDestroyNotify) gtk_widget_unref);
  selProfiles = gtk_tree_view_get_selection(GTK_TREE_VIEW (treProfiles));
  gtk_tree_selection_set_mode (selProfiles, GTK_SELECTION_SINGLE);
  gtk_widget_show (treProfiles);
  gtk_widget_set_usize (treProfiles, 250, -2);
  gtk_box_pack_start (GTK_BOX (hbMain), treProfiles, TRUE, TRUE, 0);


  gtk_signal_connect (GTK_OBJECT (entProfileName), "changed",
                      GTK_SIGNAL_FUNC (on_entries_changed),
                      GTK_OBJECT (winProfiles));
  gtk_signal_connect (GTK_OBJECT (entUsername), "changed",
                      GTK_SIGNAL_FUNC (on_entries_changed),
                      GTK_OBJECT (winProfiles));
  gtk_signal_connect (GTK_OBJECT (entPassword), "changed",
                      GTK_SIGNAL_FUNC (on_entries_changed),
                      GTK_OBJECT (winProfiles));
  gtk_signal_connect (GTK_OBJECT (entServer), "changed",
                      GTK_SIGNAL_FUNC (on_entries_changed),
                      GTK_OBJECT (winProfiles));
  gtk_signal_connect (GTK_OBJECT (btnNew), "clicked",
                      GTK_SIGNAL_FUNC (on_btnNew_clicked),
                      GTK_OBJECT (winProfiles));
  gtk_signal_connect (GTK_OBJECT (btnApply), "clicked",
                      GTK_SIGNAL_FUNC (on_btnApply_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnDelete), "clicked",
                      GTK_SIGNAL_FUNC (on_btnDelete_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnDone), "clicked",
                      GTK_SIGNAL_FUNC (on_btnDone_clicked),
                      GTK_OBJECT (winProfiles));
  g_signal_connect (G_OBJECT (selProfiles), "changed",
		      G_CALLBACK (on_profiles_changed),
		      GTK_OBJECT (winProfiles));


  return winProfiles;
}

