CCHECKERS_VERSION=0.0.3

CCHECKERS_PROTOCOL_ENGINE=CCheckers
CCHECKERS_PROTOCOL_VERSION=3

AC_SUBST(CCHECKERS_VERSION)
AC_SUBST(CCHECKERS_PROTOCOL_ENGINE)
AC_SUBST(CCHECKERS_PROTOCOL_VERSION)

AC_DEFINE_UNQUOTED([CCHECKERS_VERSION], "$CCHECKERS_VERSION",
                   [CCheckers version])
AC_DEFINE_UNQUOTED([CCHECKERS_PROTOCOL_ENGINE], "$CCHECKERS_PROTOCOL_ENGINE",
		   [CCheckers protocol engine])
AC_DEFINE_UNQUOTED([CCHECKERS_PROTOCOL_VERSION], "$CCHECKERS_PROTOCOL_VERSION",
		   [CCheckers protocol version])
