#!/bin/sh

set -e

case "$1" in
	configure*)
	#ldconfig
	update-rc.d ggzd defaults >/dev/null
	/etc/init.d/ggzd start || true
	;;
	*)
	;;
esac

# Automatically added by dh_installdocs
if [ "$1" = "configure" ]; then
	if [ -d /usr/doc -a ! -e /usr/doc/libggz-client-libs -a -d /usr/share/doc/libggz-client-libs ]; then
		ln -sf ../share/doc/libggz-client-libs /usr/doc/libggz-client-libs
	fi
fi
# End automatically added section

#DEBHELPER#

exit 0
