#!/bin/sh

set -e

/etc/init.d/ggzd stop

# Automatically added by dh_installdocs
if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/libggz-client-libs ]; then
	rm -f /usr/doc/libggz-client-libs
fi
# End automatically added section

#DEBHELPER#

exit 0
