#!/bin/sh

set -e

# Uninstall modules
for i in /usr/share/ggz/ggz-config/gtk-*; do \
	echo unregister $i; \
	ggz-config --remove --fromfile=$i || true; \
done

# Automatically added by dh_installdocs
if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/libggz-client-libs ]; then
	rm -f /usr/doc/libggz-client-libs
fi
# End automatically added section

#DEBHELPER#

exit 0
