#!/bin/sh
#
# Subversion variant for $SVN_EDITOR
# Calls the real $EDITOR but appends some stuff to the log message
# See http://svn.haxx.se/users/archive-2006-08/1261.shtml

# This script now needs sourceable configuration files at
# ~/.ggzcommit/* with the following entries:
#
# repo=svn://root/url/of/repository
# whois=1
# signature=0

# -------------------------------------------------------------------

# Checking the environment

[ $# -eq 1 ] || {
	echo "usage: $0 file"
	exit 1
} 
file=$1

ed=$VISUAL
[ -z $ed ] && ed=$EDITOR
[ -z $ed ] && ed=vi

# Load configuration file

if [ ! -d ~/.ggzcommit ]; then
	echo "Error: no configuration directory ~/.ggzcommit found"
	exit 1
fi

svnrepo=`LANG=C svn info | grep ^"Repository Root" | cut -d " " -f 3-`
for conf in ~/.ggzcommit/*; do
	. $conf
	if [ "$repo" = "$svnrepo" ]; then
		conf_repo=$repo
		conf_whois=$whois
		conf_signature=$signature
	fi
done

if [ "$svnrepo" != "$conf_repo" ]; then
	echo "Error: no configuration file found for $svnrepo"
	exit 1
fi

:> $file.$$

# Modification: Appending a whois-like signature

if [ $conf_whois ]; then

stem=`echo $file | cut -c 1-12`
if test $stem != "svn-prop.tmp"; then
HOSTNAME=`hostname`
cat << ENDTEMPLATE > $file.$$


[commit from $USER@$HOSTNAME]
ENDTEMPLATE
fi

fi

# Modification: Digital signature

if [ $conf_signature ]; then

:> $file.list.$$

lines=`cat $file`
#IFS_NEWLINE=$'\n'
IFS_NEWLINE='
'
IFS_OLD=$IFS
IFS=$IFS_NEWLINE
for line in $lines; do
	op=`echo $line | cut -d " " -f 1`
	path=`echo $line | cut -d " " -f 5-`
	if [ -f $path ]; then
		echo $path >> $file.list.$$
	elif [ -d $path ]; then
		echo $path >> $file.list.$$
	elif [ $op = "--" ]; then
		true
	else
		echo "Error: Requested file or directory $path not found."
		rm -f $file.list.$$
		exit 1
	fi
done
IFS=$IFS_OLD

IFS=$IFS_NEWLINE
svn diff `cat $file.list.$$` > $file.diff.$$
IFS=$IFS_OLD

gpg --detach-sign --armor $file.diff.$$
rm -f $file.list.$$
rm -f $file.diff.$$
if [ ! -f $file.diff.$$.asc ]; then
	echo "Error: Signature was not granted."
	exit 1
fi
cat $file.diff.$$.asc >> $file.$$
rm -f $file.diff.$$.asc

fi

# The original log message from SVN

cat $file >> $file.$$

# Finally, invoking the editor

sum=`cksum $file.$$` 
if $ed $file.$$; then 
	newsum=`cksum $file.$$` 
	if [ "$newsum" != "$sum" ]; then
		rm -f $file
		mv $file.$$ $file
	else
		# no changes
		rm -f $file.$$
	fi
else
	echo "editor \"$ed\" failed"
	exit 1
fi

