#!/bin/sh
#
# Subversion variant for $SVN_EDITOR
# Calls the real $EDITOR but appends some stuff to the log message
# See http://svn.haxx.se/users/archive-2006-08/1261.shtml
#
 
[ $# -eq 1 ] || {
	echo "usage: $0 file"
	exit 1
} 
file=$1
 
ed=$VISUAL
[ -z $ed ] && ed=$EDITOR
[ -z $ed ] && ed=vi
 
cat <<ENDTEMPLATE >$file.$$


[commit from $USER@$HOSTNAME]
ENDTEMPLATE
 
cat $file >> $file.$$
 
sum=`cksum $file.$$` 
if $ed $file.$$; then 
	newsum=`cksum $file.$$` 
	if [ "$newsum" != "$sum" ]; then
		rm -f $file
		mv $file.$$ $file
	else
		# no changes
		rm -f $file.$$
	fi
else
	echo "editor \"$ed\" failed"
	exit 1
fi

