	<div class="menubar">
		<div class="menu">
			<a href="/" class="menuitem" title="Front page">Main</a>
		</div>
		<div class="menu">
			<a href="/db/" class="menuitem" title="Game statistics and rankings">Database</a>
			<div class="menu">
				<a href="/db/" class="menuitem">Overview</a>
				<a href="/db/games/" class="menuitem">Games</a>
				<a href="/db/matches/" class="menuitem">Matches</a>
				<a href="/db/tournaments/" class="menuitem">Tournaments</a>
				<a href="/db/players/" class="menuitem">Players</a>
				<a href="/db/teams/" class="menuitem">Teams</a>
			</div>
		</div>
		<div class="menu">
			<a href="/games/" class="menuitem" title="Some online fun">Play!</a>
			<div class="menu">
				<a href="/games/" class="menuitem">GGZ games</a>
				<a href="/webgames/" class="menuitem">Web games</a>
			</div>
		</div>
		<div class="menu">
			<a href="/active/hotstuff/" class="menuitem" title="Player contributions">Manage!</a>
			<div class="menu">
				<a href="/active/hotstuff/" class="menuitem">Game contents</a>
				<a href="/active/tournaments/" class="menuitem">Tournaments</a>
				<a href="/active/teams/" class="menuitem">Teams</a>
				<a href="/active/karma/" class="menuitem">Karma</a>
			</div>
		</div>
		<div class="menu">
			<a href="/forums/" class="menuitem" title="Forums">Forums</a>
			<div class="menu">
				<a href="/forums/" class="menuitem">Community forum</a>
				<a href="/blogs/" class="menuitem">Individual blogs</a>
				<a href="/articles/" class="menuitem">Articles</a>
			</div>
		</div>
		<div class="menu">
			<a href="/contact/" class="menuitem" title="About GGZ Community">About</a>
			<div class="menu">
				<a href="/contact/" class="menuitem">Contact</a>
			</div>
		</div>
	</div>
