.TH "escape-sdl" "6" "0.0.12" "The GGZ Development Team" "GGZ Gaming Zone"
.SH "NAME"
.LP
escape-sdl \- Escape game implementation in Python/SDL for the GGZ Gaming Zone
.SH "DESCRIPTION"
.LP
The game \fIEscape\fR lets two players work on extending a common path on
a board of dots. The goal is to let the path reach the respective exit
area on the board, but difficulty ensues due to the inability to cross
existing path segments, which can be horizontal, vertical or diagonal.
.LP
Run the game from a GGZ core client to enable network players, global
highscores and more.
.SH "AUTHORS"
.LP
The GGZ Development Team
<ggz\-dev@mail.ggzgamingzone.org>
