.TH "t-rex" "1" "0.99.3" "The GGZ Development Team" "GGZ Gaming Zone"
.SH "NAME"
.LP
t-rex \- Tournament table creator for the GGZ Gaming Zone
.SH "SYNOPSIS"
.LP
.B t-rex \fIggzd.conf\fR
.SH "DESCRIPTION"
.LP
Tournaments are series of games played on the GGZ server. With \fBt-rex\fR,
the tables for each phase of the tournament can be launched automatically,
with seats reserved for the participants. This makes it much easier and
more reliable to run a tournament than having to schedule manually.
.SH "OPTIONS"
.LP
There are currently no real command line options available.
The tool needs a valid ggzd configuration file as its only argument.
.TP
\fB\-h\fR, \fB\-\-help\fR
Output usage information.
.SH "AUTHORS"
.LP
The GGZ Development Team
<ggz\-dev@mail.ggzgamingzone.org>
