.TH "xadrez-chinês" "6" "0.0.12" "The GGZ Development Team" "GGZ Gaming Zone"
.SH "NAME"
.LP
xadrez-chinês \- Chinese Chess game implementation in Python/SDL for the GGZ Gaming Zone
.SH "DESCRIPTION"
.LP
The game \fIChinese Chess\fR is a variant of the Chess game.
The board is slightly more irregular, and the pieces resemble other characters.
The gameplay is however also deeply based on strategy.
.LP
Run the game from a GGZ core client to enable network players, global
highscores and more.
.SH "AUTHORS"
.LP
The GGZ Development Team
<ggz\-dev@mail.ggzgamingzone.org>
