.TH "compcal" "6" "0.0.12" "The GGZ Development Team" "GGZ Gaming Zone"
.SH "NAME"
.LP 
compcal \- Competition Calendar for the GGZ Gaming Zone
.SH "DESCRIPTION"
.LP
The compcal tool can be used to track online game events such as
single matches, tournaments and world-wide competitions.
It gets its data from \fBGGZ Community\fR portals such as
\fIhttp://www.ggzcommunity.org/calendar/\fR in an XML format
and groups the received data to make it suitable for human
consumption.
.SH "AUTHORS"
.LP 
The GGZ Development Team
<ggz\-dev@mail.ggzgamingzone.org>
.SH "SEE ALSO"
.LP 
kggz(6)
