.TH "ggz-txt" "6" "0.0.7" "The GGZ Development Team" "GGZ Gaming Zone"
.SH "NAME"
.LP
ggz-txt \- Console-based core client for the GGZ Gaming Zone
.SH "SYNOPSIS"
.LP
.B ggz-txt
[\fIOPTIONS\fR] [\fIURI\fR]
.SH "DESCRIPTION"
.LP
This program allows one to use the GGZ without having a graphics
facility like the X11 window system.
It provides all the functionality which is needed to chat, change
rooms, view the message of the day (MOTD), and so on.
.LP
When starting ggz-txt, simply type "/connect", optionally followed
by the server host name if not running at localhost.
Alternatively, the connection URI can be given as a command line argument in
the format 'user@host:port', 'host:port' or simply 'host'.
.LP
You can always type "/help" to get a list of all available commands.
.SH "OPTIONS"
.TP
\fB-v\fR, \fB--version\fR
Display program version.
.TP
\fB-r\fR, \fB--reverse\fR
Start with alternative color scheme for reverse displays (like xterm).
.TP
\fB-h\fR, \fB--help\fR
Display some information.
.LP

.SH "AUTHORS"
.LP
The GGZ Development Team
<ggz\-dev@lists.sourceforge.net>
