REVERSI_VERSION=0.0.7

REVERSI_PROTOCOL_ENGINE=Reversi
REVERSI_PROTOCOL_VERSION=4

AC_SUBST(REVERSI_VERSION)
AC_SUBST(REVERSI_PROTOCOL_ENGINE)
AC_SUBST(REVERSI_PROTOCOL_VERSION)

AC_DEFINE_UNQUOTED([REVERSI_VERSION], "$REVERSI_VERSION", [Reversi version])
AC_DEFINE_UNQUOTED([REVERSI_PROTOCOL_ENGINE], "$REVERSI_PROTOCOL_ENGINE",
		   [Reversi protocol engine])
AC_DEFINE_UNQUOTED([REVERSI_PROTOCOL_VERSION], "$REVERSI_PROTOCOL_VERSION",
		   [Reversi protocol version])
