#!/bin/sh
#
# Utility script to invoke psql/mysql client with GGZ database connection
# Copyright (C) 2007 Josef Spillner <josef@ggzgamingzone.org>
# Published under GNU GPL conditions

ggzconfdir=`ggz-config -c`
confdirs="$ggzconfdir /etc"

unset ggzconfdir
for confdir in $confdirs; do
	if [ -d $confdir/ggzd ]; then
		ggzconfdir=$confdir/ggzd
		break
	fi
done

if [ -z $ggzconfdir ]; then
	echo "Error: GGZ configuration directory not found."
	exit 1
fi

echo "* Using $ggzconfdir..."

conffile=$ggzconfdir/ggzd.conf
dbhost=`grep ^DatabaseHost $conffile | cut -d "=" -f 2- | tr -d " "`
dbname=`grep ^DatabaseName $conffile | cut -d "=" -f 2- | tr -d " "`
dbuser=`grep ^DatabaseUsername $conffile | cut -d "=" -f 2- | tr -d " "`
dbpass=`grep ^DatabasePassword $conffile | cut -d "=" -f 2- | tr -d " "`
dbtype=`grep ^#*DatabaseType $conffile | cut -d "=" -f 2- | tr -d " "`

case $dbtype in
	"pgsql")
		PGPASSFILE=~/.pgpassfile.$$
		echo "$dbhost:*:$dbname:$dbuser:$dbpass" > $PGPASSFILE
		chmod 0600 $PGPASSFILE
		export PGPASSFILE
		psql --host=$dbhost --user=$dbuser $dbname
		rm -f $PGPASSFILE
		unset PGPASSFILE
	;;
	"mysql")
		mysql --host=$dbhost --user=$dbuser --password $dbname
		# FIXME: There doesn't seem to be a passfile mechanism
		# FIXME: and we clearly don't want it to show up in 'ps'
	;;
	*)
		echo "Error: database type is unknown."
		exit 1
	;;
esac

