<div id="main">
	<h1>
		<span class="itemleader">:: </span>
		Welcome to the Cards Community!
		<span class="itemleader"> :: </span>
		<a name="extending"></a>
	</h1>
	<div class="text">
		<table><tr><td>
		<a href="/games/applet.php"><img src="/articles/ggzcardsjava.png" border="0"></a>
		</td><td>
		Log into the site and then click on the image to the left
		in order to play directly using the GGZ-Java client.
		</td></tr></table>
	</div>
</div>
