/* Generated by GGZComm/ruby version 0.4 */
/* Protocol 'tictactoe', version '4' */
/* Do NOT edit this file! */

#ifndef GGZCOMM_TICTACTOE_H
#define GGZCOMM_TICTACTOE_H

#include <ggz_dio.h>

#define sndmove 0
#define reqsync 1
#define msgseat 0
#define msgplayers 1
#define reqmove 4
#define rspmove 5
#define msgmove 2
#define sndsync 6
#define msggameover 3

struct variables_t {
	int move_c;
	int num;
	int seat[2];
	char *name[2];
	char status;
	int player;
	int move;
	char turn;
	char space[9];
	char winner;
};
struct variables_t variables;

void ggzcomm_network_main(GGZDataIO * dio);

void ggzcomm_msgseat(GGZDataIO * dio);
void ggzcomm_msgplayers(GGZDataIO * dio);
void ggzcomm_reqmove(GGZDataIO * dio);
void ggzcomm_rspmove(GGZDataIO * dio);
void ggzcomm_msgmove(GGZDataIO * dio);
void ggzcomm_sndsync(GGZDataIO * dio);
void ggzcomm_msggameover(GGZDataIO * dio);

typedef void (*notifier_func_type) (int opcode);
typedef void (*error_func_type) (void);

void ggzcomm_set_notifier_callback(notifier_func_type f);
void ggzcomm_set_error_callback(error_func_type f);

#endif
