/* Generated by GGZComm/ruby version 0.4 */
/* Protocol 'tictactoe', version '4' */
/* Do NOT edit this file! */

#ifndef GGZCOMM_TICTACTOE_H
#define GGZCOMM_TICTACTOE_H

#define sndmove 0
#define reqsync 1
#define msgseat 0
#define msgplayers 1
#define reqmove 4
#define rspmove 5
#define msgmove 2
#define sndsync 6
#define msggameover 3
typedef struct ggzcommio_t {
	int fd;
} GGZCommIO;

struct variables_t {
	int move_c;
	int num;
	int seat[2];
	char *name[2];
	char status;
	int player;
	int move;
	char turn;
	char space[9];
	char winner;
};
struct variables_t variables;

void ggzcomm_network_main(GGZCommIO * io);

void ggzcomm_msgseat(GGZCommIO * io);
void ggzcomm_msgplayers(GGZCommIO * io);
void ggzcomm_reqmove(GGZCommIO * io);
void ggzcomm_rspmove(GGZCommIO * io);
void ggzcomm_msgmove(GGZCommIO * io);
void ggzcomm_sndsync(GGZCommIO * io);
void ggzcomm_msggameover(GGZCommIO * io);

typedef void (*notifier_func_type) (int opcode);
typedef void (*error_func_type) (void);

void ggzcomm_set_notifier_callback(notifier_func_type f);
void ggzcomm_set_error_callback(error_func_type f);

GGZCommIO *ggzcomm_io_allocate(int fd);
void ggzcomm_io_free(GGZCommIO * io);

#endif
