/* Generated by GGZComm/ruby version 0.2 */
/* Protocol 'tictactoe', version '4' */

#ifndef GGZCOMM_TICTACTOE_H
#define GGZCOMM_TICTACTOE_H

#define sndmove 0
#define reqsync 1
#define msgseat 0
#define msgplayers 1
#define reqmove 4
#define rspmove 5
#define msgmove 2
#define sndsync 6
#define msggameover 3

struct variables_t
{
	int move_c;
	int num;
	int seat[2];
	char* name[2];
	char status;
	int player;
	int move;
	char turn;
	char space[9];
	char winner;
};
struct variables_t variables;

void ggzcomm_network_main(void);

void ggzcomm_msgseat(void);
void ggzcomm_msgplayers(void);
void ggzcomm_reqmove(void);
void ggzcomm_rspmove(void);
void ggzcomm_msgmove(void);
void ggzcomm_sndsync(void);
void ggzcomm_msggameover(void);

typedef void (*notifier_func_type)(int opcode);
typedef void (*error_func_type)(void);

void ggzcomm_set_fd(int usefd);
int  ggzcomm_get_fd(void);
void ggzcomm_set_notifier_callback(notifier_func_type f);
void ggzcomm_set_error_callback(error_func_type f);

#endif

