	<div class="text">
	Game information and statistics about all registered GGZ players 
	can be seen by clicking a player in the list on the right side.
	</div>
	<div class="text">
	<?php include("intro.php"); ?>
	<?php player_intro(); ?>
	</div>
	<div class="text">
	If you want to find certain players from your country, or with
	similar skills, or high rankings in some game, check out the
	<a href="playerfinder.php">player finder</a>.
	</div>
