	<h1>
		<span class="itemleader">:: </span>
GGZ Community Blogs		<span class="itemleader"> :: </span>
		<a name="planet"></a>
	</h1>


	<h2>
		<span class="itemleader">:: </span>
January 05, 2005		<span class="itemleader"> :: </span>
		<a name="planetdate"></a>
	</h2>

	<div class="text">

<a href="http://www.holarse.net" title="Holarse - Spielen unter Linux">
Holarse - Spielen unter Linux</a>

:
<a href="http://www.holarse.de/?news=315">
Does Linux Have Game ?</a>

	<br>

<a href="http://www.holarse.de/?news=315">January 05, 2005 07:12 PM</a>


	</div>
	<div class="text">

Does Linux Have Game ?  mehr lesen!
	</div>



	<div class="text">

<a href="http://www.holarse.net" title="Holarse - Spielen unter Linux">
Holarse - Spielen unter Linux</a>

:
<a href="http://www.holarse.de/?news=314">
UFO AI Christmas Edition</a>

	<br>

<a href="http://www.holarse.de/?news=314">January 05, 2005 08:16 AM</a>


	</div>
	<div class="text">

UFO AI Christmas Edition mehr lesen!
	</div>


	<h2>
		<span class="itemleader">:: </span>
January 03, 2005		<span class="itemleader"> :: </span>
		<a name="planetdate"></a>
	</h2>

	<div class="text">

<a href="http://www.holarse.net" title="Holarse - Spielen unter Linux">
Holarse - Spielen unter Linux</a>

:
<a href="http://www.holarse.de/?news=313">
&#x22;Neue&#x22; Demos</a>

	<br>

<a href="http://www.holarse.de/?news=313">January 03, 2005 06:32 PM</a>


	</div>
	<div class="text">

&#x22;Neue&#x22; Demos mehr lesen!
	</div>


	<h2>
		<span class="itemleader">:: </span>
January 02, 2005		<span class="itemleader"> :: </span>
		<a name="planetdate"></a>
	</h2>

	<div class="text">

<a href="http://www.holarse.net" title="Holarse - Spielen unter Linux">
Holarse - Spielen unter Linux</a>

:
<a href="http://www.holarse.de/?news=312">
Quake3-Engine unter GPL in Vorbereitung</a>

	<br>

<a href="http://www.holarse.de/?news=312">January 02, 2005 12:09 PM</a>


	</div>
	<div class="text">

Quake3-Engine unter GPL in Vorbereitung mehr lesen!
	</div>


	<h2>
		<span class="itemleader">:: </span>
January 01, 2005		<span class="itemleader"> :: </span>
		<a name="planetdate"></a>
	</h2>

	<div class="text">

<a href="http://www.holarse.net" title="Holarse - Spielen unter Linux">
Holarse - Spielen unter Linux</a>

:
<a href="http://www.holarse.de/?news=311">
Happy 2005!</a>

	<br>

<a href="http://www.holarse.de/?news=311">January 01, 2005 07:49 AM</a>


	</div>
	<div class="text">

Happy 2005! mehr lesen!
	</div>


	<h2>
		<span class="itemleader">:: </span>
December 30, 2004		<span class="itemleader"> :: </span>
		<a name="planetdate"></a>
	</h2>

	<div class="text">

<a href="http://www.holarse.net" title="Holarse - Spielen unter Linux">
Holarse - Spielen unter Linux</a>

:
<a href="http://www.holarse.de/?news=310">
Anarchy Online Classic</a>

	<br>

<a href="http://www.holarse.de/?news=310">December 30, 2004 12:41 PM</a>


	</div>
	<div class="text">

Anarchy Online Classic mehr lesen!
	</div>


	<h2>
		<span class="itemleader">:: </span>
December 27, 2004		<span class="itemleader"> :: </span>
		<a name="planetdate"></a>
	</h2>

	<div class="text">

<a href="http://www.holarse.net" title="Holarse - Spielen unter Linux">
Holarse - Spielen unter Linux</a>

:
<a href="http://www.holarse.de/?news=309">
Unsichere Zukunft für doom3linux.de</a>

	<br>

<a href="http://www.holarse.de/?news=309">December 27, 2004 09:12 AM</a>


	</div>
	<div class="text">

Unsichere Zukunft für doom3linux.de mehr lesen!
	</div>


	<h2>
		<span class="itemleader">:: </span>
December 26, 2004		<span class="itemleader"> :: </span>
		<a name="planetdate"></a>
	</h2>

	<div class="text">

<a href="http://www.holarse.net" title="Holarse - Spielen unter Linux">
Holarse - Spielen unter Linux</a>

:
<a href="http://www.holarse.de/?news=308">
Kernel 2.6.10 / nVidia 6629</a>

	<br>

<a href="http://www.holarse.de/?news=308">December 26, 2004 06:58 PM</a>


	</div>
	<div class="text">

Kernel 2.6.10 / nVidia 6629 mehr lesen!
	</div>


	<h2>
		<span class="itemleader">:: </span>
December 25, 2004		<span class="itemleader"> :: </span>
		<a name="planetdate"></a>
	</h2>

	<div class="text">

<a href="http://www.holarse.net" title="Holarse - Spielen unter Linux">
Holarse - Spielen unter Linux</a>

:
<a href="http://www.holarse.de/?news=307">
Neuer Bericht: City of Heroes (Open Beta)</a>

	<br>

<a href="http://www.holarse.de/?news=307">December 25, 2004 10:00 AM</a>


	</div>
	<div class="text">

Neuer Bericht: City of Heroes (Open Beta) mehr lesen!
	</div>


	<h2>
		<span class="itemleader">:: </span>
December 24, 2004		<span class="itemleader"> :: </span>
		<a name="planetdate"></a>
	</h2>

	<div class="text">

<a href="http://www.holarse.net" title="Holarse - Spielen unter Linux">
Holarse - Spielen unter Linux</a>

:
<a href="http://www.holarse.de/?news=306">
ScummVM James Bond Release 0.7.0</a>

	<br>

<a href="http://www.holarse.de/?news=306">December 24, 2004 11:40 PM</a>


	</div>
	<div class="text">

ScummVM James Bond Release 0.7.0 mehr lesen!
	</div>



	<div class="text">

<a href="http://www.holarse.net" title="Holarse - Spielen unter Linux">
Holarse - Spielen unter Linux</a>

:
<a href="http://www.holarse.de/?news=305">
Holarse Weihnachtsgruss 2004</a>

	<br>

<a href="http://www.holarse.de/?news=305">December 24, 2004 09:54 AM</a>


	</div>
	<div class="text">

Holarse Weihnachtsgruss 2004 mehr lesen!
	</div>


	<h2>
		<span class="itemleader">:: </span>
December 22, 2004		<span class="itemleader"> :: </span>
		<a name="planetdate"></a>
	</h2>

	<div class="text">

<a href="http://www.holarse.net" title="Holarse - Spielen unter Linux">
Holarse - Spielen unter Linux</a>

:
<a href="http://www.holarse.de/?news=304">
Neuer Bericht: World of Padman</a>

	<br>

<a href="http://www.holarse.de/?news=304">December 22, 2004 07:52 PM</a>


	</div>
	<div class="text">

Neuer Bericht: World of Padman mehr lesen!
	</div>



	<div class="text">

<a href="http://www.holarse.net" title="Holarse - Spielen unter Linux">
Holarse - Spielen unter Linux</a>

:
<a href="http://www.holarse.de/?news=303">
Uplink deutsch und Robin Hood englisch</a>

	<br>

<a href="http://www.holarse.de/?news=303">December 22, 2004 03:32 PM</a>


	</div>
	<div class="text">

Uplink deutsch und Robin Hood englisch mehr lesen!
	</div>



	<div class="text">

<a href="http://www.holarse.net" title="Holarse - Spielen unter Linux">
Holarse - Spielen unter Linux</a>

:
<a href="http://www.holarse.de/?news=302">
Airline Tycoon Deluxe für Mac und Linux</a>

	<br>

<a href="http://www.holarse.de/?news=302">December 22, 2004 01:05 PM</a>


	</div>
	<div class="text">

Airline Tycoon Deluxe für Mac und Linux mehr lesen!
	</div>



	<div class="text">

<a href="http://www.holarse.net" title="Holarse - Spielen unter Linux">
Holarse - Spielen unter Linux</a>

:
<a href="http://www.holarse.de/?news=301">
Arydox: Project Golden Hawk 1.1</a>

	<br>

<a href="http://www.holarse.de/?news=301">December 22, 2004 01:37 AM</a>


	</div>
	<div class="text">

Arydox: Project Golden Hawk 1.1 mehr lesen!
	</div>


	<h2>
		<span class="itemleader">:: </span>
December 21, 2004		<span class="itemleader"> :: </span>
		<a name="planetdate"></a>
	</h2>

	<div class="text">

<a href="http://www.holarse.net" title="Holarse - Spielen unter Linux">
Holarse - Spielen unter Linux</a>

:
<a href="http://www.holarse.de/?news=300">
Anandtech Roundup Part two</a>

	<br>

<a href="http://www.holarse.de/?news=300">December 21, 2004 02:06 AM</a>


	</div>
	<div class="text">

Anandtech Roundup Part two mehr lesen!
	</div>


	<h2>
		<span class="itemleader">:: </span>
December 07, 2004		<span class="itemleader"> :: </span>
		<a name="planetdate"></a>
	</h2>

	<div class="text">

<a href="http://www.ggzgamingzone.org/~josef/" title="Josef Spillner">
Josef Spillner</a>

:
<a href="http://www.ggzgamingzone.org/~josef/">
I'm blogging!</a>

	<br>

<a href="http://www.ggzgamingzone.org/~josef/">December 07, 2004 12:23 AM</a>


	</div>
	<div class="text">

For the sake of starting to fill some feed aggregators,
here will be my GGZ blog from now on.
	</div>


