/*
 * File: callbacks.c
 * Author: Brent Hendricks
 * Project: GGZ Client
 * Date: 2/18/00
 *
 * This file contains callbacks for GTK windows generated by glade
 *
 * Copyright (C) 1998 Brent Hendricks.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>

#include "connect.h"
#include "dlg_error.h"
#include "protocols.h"
#include "datatypes.h"
#include "game.h"
#include "callbacks.h"
#include "support.h"
#include "err_func.h"

#include "dlg_details.h"
#include "dlg_launch.h"

/* Global data */
extern GtkWidget *detail_window;
extern GtkWidget *main_win;
extern GtkWidget *dlg_launch;
extern struct ConnectInfo connection;
extern int selected_table;
extern int selected_type;
extern struct GameTypes game_types;


/*				*
 *	Login dialog		*
 *				*/

void login_anon_toggled(GtkWidget* button, gpointer window) 
{
	gpointer tmp;
	tmp = gtk_object_get_data(GTK_OBJECT(window), "pass_box");
	
	if (GTK_TOGGLE_BUTTON(button)->active)
		gtk_widget_hide(GTK_WIDGET(tmp));
	else 
		gtk_widget_show(GTK_WIDGET(tmp));
}


void login_fill_defaults(GtkWidget * win, gpointer user_data)
{
	gpointer *tmp;
	char port[5];

	tmp = gtk_object_get_data(GTK_OBJECT(win), "name_entry");
	if (connection.username)
		gtk_entry_set_text(GTK_ENTRY(tmp), connection.username);
	else 
		gtk_entry_set_text(GTK_ENTRY(tmp), getenv("LOGNAME"));
		

	tmp = gtk_object_get_data(GTK_OBJECT(win), "host_entry");
	if (connection.server)
		gtk_entry_set_text(GTK_ENTRY(tmp), connection.server);
	else
		gtk_entry_set_text(GTK_ENTRY(tmp), "localhost");

	tmp = gtk_object_get_data(GTK_OBJECT(win), "port_entry");
	if (connection.port) {
		snprintf(port, 5, "%d", connection.port);
		gtk_entry_set_text(GTK_ENTRY(tmp), port);
	}
	else
		gtk_entry_set_text(GTK_ENTRY(tmp), "7626");

	tmp = gtk_object_get_data(GTK_OBJECT(win), "anon_radio");
	gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(tmp), TRUE);
}


void login_input_options(GtkButton * button, gpointer window)
{
        gpointer tmp;

	tmp = gtk_object_get_data(GTK_OBJECT(window), "name_entry");
	connection.username = g_strdup(gtk_entry_get_text(GTK_ENTRY(tmp)));

	tmp = gtk_object_get_data(GTK_OBJECT(window), "pass_entry");
	connection.password = g_strdup(gtk_entry_get_text(GTK_ENTRY(tmp)));
	
	tmp = gtk_object_get_data(GTK_OBJECT(window), "host_entry");
	connection.server = g_strdup(gtk_entry_get_text(GTK_ENTRY(tmp)));

	tmp = gtk_object_get_data(GTK_OBJECT(window), "port_entry");
	connection.port = atoi(gtk_entry_get_text(GTK_ENTRY(tmp)));
	
	tmp = gtk_object_get_data(GTK_OBJECT(window), "normal_radio");
	if (GTK_TOGGLE_BUTTON(tmp)->active)
		connection.login_type = GGZ_LOGIN;

	tmp = gtk_object_get_data(GTK_OBJECT(window), "anon_radio");
	if (GTK_TOGGLE_BUTTON(tmp)->active)
		connection.login_type = GGZ_LOGIN_ANON;

	tmp = gtk_object_get_data(GTK_OBJECT(window), "first_radio");
	if (GTK_TOGGLE_BUTTON(tmp)->active)
		connection.login_type = GGZ_LOGIN_NEW;
}


void login_start_session(GtkButton * button, gpointer window)
{
	if (connection.connected) {
		warn_dlg("Already Connected.");
		return;
	}
	
	/* FIXME: Initialize for new game session */
	
	if (connect_to_server() < 0) {
		err_dlg("Could not connect");
		return;
	}

	/* Close connect dialog if we were successful */
	connection.connected = TRUE;
	gtk_widget_destroy(GTK_WIDGET(window));

	/*FIXME: Other session starting things ? */
}


void login_show_details(GtkButton * button, gpointer user_data)
{
	detail_window = create_dlg_details();
	gtk_widget_show(detail_window);
}


/*				*
 *	Details dialog		*
 *				*/

void details_cancel_details(GtkButton * button, gpointer user_data)
{
	gtk_widget_destroy(detail_window);
	detail_window = NULL;
}


/*				*
 *	Launch Game dialog	*
 *				*/

void launch_change_type(GtkCombo *type_combo, gpointer user_data)
{
	GtkWidget *temp_widget;
	int i;
	int type_index=0;

	/* FIXME: If the game HAS to have a total of n players
		remove the "Closed" option from the drop down.
	*/

	/* Get new game type index */
        temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo1");
	for(i=0;i<game_types.count;i++)
	{
		if(!strcmp(game_types.info[i].name,gtk_entry_get_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry))))
		{
			type_index = i;
		}
	}

	/* Set all combos on */
	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo10");
	gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 1);
	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo9");
	gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 1);
	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo8");
	gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 1);
	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo7");
	gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 1);
	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo6");
	gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 1);
	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo5");
	gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 1);
	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo4");
	gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 1);
	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo2");
	gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 1);
	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo1");
	gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 1);

	if (game_types.info[0].num_play_allow == (char) PLAY_ALLOW_EIGHT)
	{
	        temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo10");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
		temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo9");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	}else if (game_types.info[type_index].num_play_allow == (char) PLAY_ALLOW_SEVEN)
	{
	        temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo10");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo9");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo8");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	}else if (game_types.info[type_index].num_play_allow == (char) PLAY_ALLOW_SIX)
	{
	        temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo10");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo9");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo8");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo7");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	}else if (game_types.info[type_index].num_play_allow == (char) PLAY_ALLOW_FIVE)
	{
	        temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo10");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo9");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo8");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	       	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo7");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo6");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	}else if (game_types.info[type_index].num_play_allow == (char) PLAY_ALLOW_FOUR)
	{
	        temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo10");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo9");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo8");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo7");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo6");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo5");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	}else if (game_types.info[type_index].num_play_allow == (char) PLAY_ALLOW_THREE)
	{
	        temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo10");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo9");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo8");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo7");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo6");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo5");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo4");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	}else if (game_types.info[type_index].num_play_allow == (char) PLAY_ALLOW_TWO)
	{
	        temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo10");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo9");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo8");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo7");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo6");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo5");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo4");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo2");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	}else if (game_types.info[type_index].num_play_allow == (char) PLAY_ALLOW_ONE)
	{
	        temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo10");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo9");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo8");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo7");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo6");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo5");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo4");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo2");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo1");
		gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
		gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	}
}

void launch_start_game(GtkWidget *btn_launch, gpointer user_data)
{
	GtkWidget *temp_widget;
	int i;
        int launch_game_type=0;
        
	/* Hide it at this point, we still nead 
	   it there to get the information from */
	gtk_widget_hide(GTK_OBJECT(dlg_launch));

        /* Get game type to play */
        temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo1");
        for(i=0;i<game_types.count;i++)
        {
                if(!strcmp(game_types.info[i].name,
                   gtk_entry_get_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry))))
                        launch_game_type= i;
        }

	if (!connection.connected)
		warn_dlg("Not connected!");
	else {
		launch_game(launch_game_type,1);
	}

}

/*				*
 *	Main GGZ client window	*
 *				*/

void ggz_get_game_options(GtkButton * button, gpointer user_data)
{

	GtkWidget *temp_widget;
	GList *combo_items = NULL;
	int count;

	if (!connection.connected)
		warn_dlg("Not connected!");
	else {
		dlg_launch = create_dlgLaunch();
	        temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "lblUser");
		gtk_label_set_text (GTK_LABEL (temp_widget), connection.username);
		for (count=0; count<game_types.count; count++){
			combo_items = g_list_append (combo_items, game_types.info[count].name);
		}
	        temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo1");
		gtk_combo_set_popdown_strings (GTK_COMBO (temp_widget), combo_items);
		g_list_free (combo_items);

		/* Setup combos for game type 0 as the starting place
		   The dialog will default to ame type 0 until the player
		   changes the game type.
		*/

		if (game_types.info[0].num_play_allow == (char) PLAY_ALLOW_EIGHT)
		{
		        temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo10");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo9");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
		}else if (game_types.info[0].num_play_allow == (char) PLAY_ALLOW_SEVEN)
		{
		        temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo10");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo9");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo8");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
		}else if (game_types.info[0].num_play_allow == (char) PLAY_ALLOW_SIX)
		{
		        temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo10");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo9");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo8");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo7");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
		}else if (game_types.info[0].num_play_allow == (char) PLAY_ALLOW_FIVE)
		{
		        temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo10");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo9");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo8");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo7");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo6");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
		}else if (game_types.info[0].num_play_allow == (char) PLAY_ALLOW_FOUR)
		{
		        temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo10");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo9");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo8");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo7");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo6");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo5");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
		}else if (game_types.info[0].num_play_allow == (char) PLAY_ALLOW_THREE)
		{
		        temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo10");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo9");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo8");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo7");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo6");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo5");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo4");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
		}else if (game_types.info[0].num_play_allow == (char) PLAY_ALLOW_TWO)
		{
		        temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo10");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo9");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo8");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo7");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo6");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo5");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo4");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo2");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
		}else if (game_types.info[0].num_play_allow == (char) PLAY_ALLOW_ONE)
		{
		        temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo10");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo9");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo8");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo7");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo6");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo5");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo4");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo2");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
	        	temp_widget = gtk_object_get_data(GTK_OBJECT(dlg_launch), "combo1");
			gtk_entry_set_text(GTK_ENTRY(GTK_COMBO(temp_widget)->entry),"Closed");
			gtk_widget_set_sensitive (GTK_WIDGET (temp_widget), 0);
		}

		gtk_widget_show(dlg_launch);
	}

}

void ggz_join_game(GtkButton * button, gpointer user_data)
{
	dbg_msg("joining game");
	es_write_int(connection.sock, REQ_TABLE_JOIN);
	es_write_int(connection.sock, selected_table);
}

void ggz_logout(GtkMenuItem * menuitem, gpointer user_data)
{
	dbg_msg("Logging out");
	es_write_int(connection.sock, REQ_LOGOUT);
}


void ggz_get_types(GtkMenuItem * menuitem, gpointer user_data)
{
	char verbose = 1;

	es_write_int(connection.sock, REQ_LIST_TYPES);
	write(connection.sock, &verbose, 1);
}


void ggz_get_players(GtkMenuItem * menuitem, gpointer user_data)
{
	es_write_int(connection.sock, REQ_LIST_PLAYERS);
}


void ggz_get_tables(GtkMenuItem * menuitem, gpointer user_data)
{
	es_write_int(connection.sock, REQ_LIST_TABLES);
	es_write_int(connection.sock, -1);
}


void ggz_input_chat_msg(GtkWidget * widget, gpointer user_data)
{
	if (!connection.connected) {
		err_dlg("Not Connected");
		return;
	}
	
	if (strcmp(gtk_entry_get_text(GTK_ENTRY(user_data)), "") != 0
	    && es_write_int(connection.sock, REQ_CHAT) > 0)
		
		es_write_string(connection.sock,
				gtk_entry_get_text(GTK_ENTRY(user_data)));
	
	gtk_entry_set_text(GTK_ENTRY(user_data), "");
}


void ggz_table_select_row_callback(GtkWidget *widget, gint row, gint column,
			       GdkEventButton *event, gpointer data)
{
	gchar *text;
	int i;

	gtk_clist_get_text(GTK_CLIST(widget), row, 1, &text);
	selected_table = atoi(text);
	gtk_clist_get_text(GTK_CLIST(widget), row, 2, &text);
	for(i=0;i<game_types.count;i++)
	{
		if(!strcmp(text,game_types.info[i].name))
			selected_type=i;
	}
}


