/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "client.h"
#include "interface.h"
#include "support.h"
#include "options.h"
#include "parse_opt.h"


Options opt;

int
main (int argc, char *argv[])
{
  GtkWidget *dlg_login;
  GtkWidget *main_win;

  parse_args(argc, argv);

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/pixmaps");
  add_pixmap_directory (PACKAGE_SOURCE_DIR "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  main_win = create_main_win ();
  gtk_widget_show (main_win);
  dlg_login = create_dlg_login ();
  gtk_widget_show (dlg_login);
  
  gtk_main ();
  return 0;
}


