prefix = /usr/local
srcdir = .
top_builddir = ..
subdir = po

XGETTEXT = xgettext
MSGMERGE = msgmerge
MSGFMT = msgfmt

CATALOG = ggzpython
POSOURCES = ../lib/sdlnewstuff.py ../lib/playertable.py ../ggzboard/ggzboard ../ggzboard/module_*.py
POFLAGS = -LPython

include i18n.mk

install: install-data-local
