/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include <main_win.h>
#include <support.h>

GtkWidget *main_win;
GdkPixmap* ttt_buf;

extern int send_my_move(int move);
extern int move;

void game_status( const char* format, ... ) 
{
	int id;
	va_list ap;
	char* message;
	gpointer tmp;

	va_start( ap, format);
	message = g_strdup_vprintf(format, ap);
	va_end(ap);
	
	tmp = gtk_object_get_data(GTK_OBJECT(main_win), "statusbar");
	
	id = gtk_statusbar_get_context_id( GTK_STATUSBAR(tmp), "Main" );
	
	gtk_statusbar_pop( GTK_STATUSBAR(tmp), id );
	gtk_statusbar_push( GTK_STATUSBAR(tmp), id, message );
	
	g_free( message );
	
}


gboolean main_exit(GtkWidget *widget, GdkEvent *event, gpointer user_data)
{
	/* FIXME: should call an "are you sure dialog" */
	gtk_main_quit();
	
	return FALSE;
}


void
game_resync                            (GtkMenuItem     *menuitem,
                                        gpointer         user_data)
{

}


void game_exit(GtkMenuItem *menuitem, gpointer user_data)
{
	/* FIXME: should call an "are you sure dialog" */
	gtk_main_quit();

}


void
game_about                             (GtkMenuItem     *menuitem,
                                        gpointer         user_data)
{

}


gboolean configure_handle(GtkWidget *widget, GdkEventConfigure *event, 
			  gpointer user_data)
{
	fprintf(stderr, "Handling config event\n");
	
	if (ttt_buf)
		gdk_pixmap_unref(ttt_buf);
	else {
		ttt_buf = gdk_pixmap_new( widget->window,
					  widget->allocation.width,
					  widget->allocation.height,
					  -1);
		gdk_draw_rectangle( ttt_buf,
				    widget->style->black_gc,
				    TRUE,
				    0, 0,
				    widget->allocation.width,
				    widget->allocation.height);
		
		gdk_draw_line(ttt_buf, 
			      widget->style->white_gc,
			      70, 10,
			      70, 190);

		gdk_draw_line(ttt_buf, 
			      widget->style->white_gc,
			      130, 10,
			      130, 190);

		gdk_draw_line(ttt_buf, 
			      widget->style->white_gc,
			      10, 70,
			      190, 70);

		gdk_draw_line(ttt_buf, 
			      widget->style->white_gc,
			      10, 130,
			      190, 130);

	}
	
	return TRUE;
}


gboolean expose_handle(GtkWidget *widget, GdkEventExpose  *event, 
		       gpointer user_data)
{
	fprintf(stderr, "Handling expose event\n");

	gdk_draw_pixmap( widget->window,
			 widget->style->fg_gc[GTK_WIDGET_STATE (widget)],
			 ttt_buf,
			 event->area.x, event->area.y,
			 event->area.x, event->area.y,
			 event->area.width, event->area.height);
	
	return FALSE;
}


gboolean get_move(GtkWidget *widget, GdkEventButton  *event, 
		       gpointer user_data)
{
	int x = (int)(event->x);
	int y = (int)(event->y);
	int col = (x - 10) / 60;
	int row = (y - 10) / 60;
	
	if (event->button == 1 && ttt_buf != NULL) {
		g_print("Mouse click at (%d, %d)\n", x, y);
		if (col == 3)
			col = 2;
		if (row == 3)
			row = 2;
		
		move = row * 3 + col;
		g_print("Mouse click at (%d, %d)\n", col, row);
		g_print("Move = %d\n", move);
		
		send_my_move(move);

#if 0
    /* If it's our turn to play a card...*/
    if( gameState.gameSegment == ST_GET_TRICK && 
       gameState.curPlayer == gameState.playerId ) {
      
      /* Put handIndex in the range of 0-12 */
      handIndex = (x-(x%20))/20;
      if( handIndex > 12 ) {
	handIndex = 12;
      }
      
      /* Back up one if we get an "already played" */
      while( handIndex >0 && gameState.hand[handIndex] == BLANK_CARD ) {
	handIndex--;
      }
	
      /* Don't allow negative numbers */
      if( handIndex < 0 ) {
	handIndex = 0;
      }

      /* If we're not in the right card, go back to an invalid one */
      if( x - (handIndex*20) > CARDWIDTH ) {
	handIndex++;
      }
      
      status = SendCard( handIndex );
      
      switch( status ) {

      case -1: /* Card already played */
	DisplayStatusLine( "You already played that card" );
	break;
      case -2: /* Renege */
	DisplayStatusLine( "Hey, no cheating, you're not out yet" );
	break;
      case 0: /* Card ok */
	DisplayPlayedCard( gameState.hand[handIndex], 0, 0);
	HideCard( handIndex );
	UpdateGame();
	ClearStatusLine();
	break;
      }
    } /* if it's our turn to play*/
#endif
  } /* if left-click and drawing area != NULL*/

  return TRUE;
  
}

GtkWidget*
create_main_win (void)
{
  GtkWidget *main_box;
  GtkWidget *menubar;
  guint tmp_key;
  GtkWidget *game_menuhead;
  GtkWidget *game_menu;
  GtkAccelGroup *game_menu_accels;
  GtkWidget *resync;
  GtkWidget *exit;
  GtkWidget *help_menuhead;
  GtkWidget *help_menu;
  GtkAccelGroup *help_menu_accels;
  GtkWidget *about;
  GtkWidget *drawingarea;
  GtkWidget *statusbar;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  main_win = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (main_win), "main_win", main_win);
  gtk_window_set_title (GTK_WINDOW (main_win), _("Tic-Tac-Toe"));

  main_box = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (main_box);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "main_box", main_box,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (main_box);
  gtk_container_add (GTK_CONTAINER (main_win), main_box);

  menubar = gtk_menu_bar_new ();
  gtk_widget_ref (menubar);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "menubar", menubar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar);
  gtk_box_pack_start (GTK_BOX (main_box), menubar, FALSE, FALSE, 0);

  game_menuhead = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (game_menuhead)->child),
                                   _("_Game"));
  gtk_widget_add_accelerator (game_menuhead, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (game_menuhead);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "game_menuhead", game_menuhead,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (game_menuhead);
  gtk_container_add (GTK_CONTAINER (menubar), game_menuhead);

  game_menu = gtk_menu_new ();
  gtk_widget_ref (game_menu);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "game_menu", game_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (game_menuhead), game_menu);
  game_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (game_menu));

  resync = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (resync)->child),
                                   _("Re_sync"));
  gtk_widget_add_accelerator (resync, "activate_item", game_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (resync);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "resync", resync,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (resync);
  gtk_container_add (GTK_CONTAINER (game_menu), resync);

  exit = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (exit)->child),
                                   _("E_xit"));
  gtk_widget_add_accelerator (exit, "activate_item", game_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (exit);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "exit", exit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exit);
  gtk_container_add (GTK_CONTAINER (game_menu), exit);

  help_menuhead = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (help_menuhead)->child),
                                   _("_Help"));
  gtk_widget_add_accelerator (help_menuhead, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (help_menuhead);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "help_menuhead", help_menuhead,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (help_menuhead);
  gtk_container_add (GTK_CONTAINER (menubar), help_menuhead);
  gtk_menu_item_right_justify (GTK_MENU_ITEM (help_menuhead));

  help_menu = gtk_menu_new ();
  gtk_widget_ref (help_menu);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "help_menu", help_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help_menuhead), help_menu);
  help_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (help_menu));

  about = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (about)->child),
                                   _("_About"));
  gtk_widget_add_accelerator (about, "activate_item", help_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (about);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "about", about,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (about);
  gtk_container_add (GTK_CONTAINER (help_menu), about);

  drawingarea = gtk_drawing_area_new ();
  gtk_drawing_area_size(GTK_DRAWING_AREA(drawingarea), 200, 200);

  gtk_widget_ref (drawingarea);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "drawingarea", drawingarea,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (drawingarea);
  gtk_box_pack_start (GTK_BOX (main_box), drawingarea, TRUE, TRUE, 0);

  statusbar = gtk_statusbar_new ();
  gtk_widget_ref (statusbar);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "statusbar", statusbar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (statusbar);
  gtk_box_pack_start (GTK_BOX (main_box), statusbar, FALSE, FALSE, 0);

  gtk_signal_connect (GTK_OBJECT (main_win), "delete_event",
                      GTK_SIGNAL_FUNC (main_exit),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (resync), "activate",
                      GTK_SIGNAL_FUNC (game_resync),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (exit), "activate",
                      GTK_SIGNAL_FUNC (game_exit),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (about), "activate",
                      GTK_SIGNAL_FUNC (game_about),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (drawingarea), "configure_event",
                      GTK_SIGNAL_FUNC (configure_handle),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (drawingarea), "expose_event",
                      GTK_SIGNAL_FUNC (expose_handle),
                      NULL);

  gtk_signal_connect (GTK_OBJECT(drawingarea), "button_press_event",
		      GTK_SIGNAL_FUNC(get_move), 
		      NULL );

  gtk_widget_set_events(drawingarea, GDK_EXPOSURE_MASK | GDK_BUTTON_PRESS_MASK );  
  gtk_window_add_accel_group (GTK_WINDOW (main_win), accel_group);

  return main_win;
}

