HASTINGS_VERSION=0.0.7

HASTINGS_PROTOCOL_ENGINE=Hastings
HASTINGS_PROTOCOL_VERSION=4

AC_SUBST(HASTINGS_VERSION)
AC_SUBST(HASTINGS_PROTOCOL_ENGINE)
AC_SUBST(HASTINGS_PROTOCOL_VERSION)

AC_DEFINE_UNQUOTED([HASTINGS_VERSION], "$HASTINGS_VERSION", [Hastings version])
AC_DEFINE_UNQUOTED([HASTINGS_PROTOCOL_ENGINE], "$HASTINGS_PROTOCOL_ENGINE",
		   [Hastings protocol engine])
AC_DEFINE_UNQUOTED([HASTINGS_PROTOCOL_VERSION], "$HASTINGS_PROTOCOL_VERSION",
		   [Hastings protocol version])
