<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>
GGZ Gaming Zone Tournaments
</title>
</head>
<body bgcolor='#00a000' link='#000000' alink='#000000' vlink='#000000'>


<table border=0 cellspacing=0 cellpadding=1 width='100%'><tr><td bgcolor='#000000'>
<table border=0 cellspacing=0 cellpadding=5 width='100%'><tr><td bgcolor='#00ff00'>
<a href='index.php'><img src='ggzlogogreen.png' align='middle' border=0 alt="ggzlogo"></a>
&nbsp;&nbsp;
<font color='#000000' size=5>
GGZ Gaming Zone Tournaments
</font>
</td></tr></table>
</td></tr></table>
<br><br>

<table border=0 width='100%'><tr><td valign=top>

<?php
include('.htconf');
?>

