.TH "ggzwrap" "1" "0.0.8" "The GGZ Development Team" "GGZ Gaming Zone"
.SH "NAME"
.LP
ggzwrap \- A generic game client/server wrapper
.SH "SYNOPSIS"
.LP
ggzwrap
\-\-fdin=FDIN \-\-fdout=FDOUT \-\-exec=PROGRAM [\fI\-\-convert\fR]
.SH "DESCRIPTION"
.LP
This wrapper takes the place of a game client and server. Its task is to manage
different file descriptors than the one which are normally used.
The GGZ servers and clients do currently communicate using fd 3, so a call to:
.LP
\fBggzwrap \-\-fdin=3 \-\-fdout=3 \-\-exec=gameserver\fR
.LP
would be equivalent to calling the server directly. However, there are games
which communicate using the standard input/output facilities, so they need a
redirection like:
.LP
\fBggzwrap \-\-fdin=0 \-\-fdout=1 \-\-exec=gameserver\fR
.LP
The \fI\-\-convert\fR option tries to automatically convert strings from network format
to host format (more correctly, from libggz's easysock format to the normal
null-terminated one).
.SH "AUTHORS"
.LP
The GGZ Development Team
<ggz\-dev@mail.ggzgamingzone.org>
.SH "SEE ALSO"
.LP
shadowbridge(6)
