.TH "muehle-ai.pl" "6" "0.0.8" "The GGZ Development Team" "GGZ Gaming Zone"
.SH "NAME"
.LP
muehle-ai.pl \- AI for the GGZ muehle game
.SH "DESCRIPTION"
.LP
Using standard input/output facilities, this game works as an artificial
intelligence (AI) for the Muehle game which is part of the GGZ Gaming Zone.
.SH "AUTHORS"
.LP
The GGZ Development Team
<ggz\-dev@mail.ggzgamingzone.org>
shadowbridge(6)
