.TH "ggz-gnome" "6" "0.0.12" "The GGZ Development Team" "GGZ Gaming Zone"
.SH "NAME"
.LP
ggz-gnome \- GNOME core client for the GGZ Gaming Zone
.SH "SYNOPSIS"
.LP
.B ggz-gnome
[\fIURL\fR]
.SH "DESCRIPTION"
.LP
This is the GNOME frontend for the GGZ Gaming Zone, and a
"brother" of \fBkggz\fR, \fBggz-gtk\fR and \fBggz-txt\fR.
The purpose of ggz-gnome is to allow an easy access to GGZ Gaming Zone
servers. After the program start, a login dialog appears, where
one can either register or log in as guest player or registered
player.
After having logged in, one can chat with other players and
play some games with them.
.LP
A connection \fIURL\fR like ggz://username@host:port can be given as argument.
In such a case ggz-gnome will connect directly to the GGZ server.
.SH "FILES"
.LP
\fI$HOME/.ggz/ggz-gnome.rc\fP - configuration
.SH "BUGS"
.LP
This application is currently not well maintained.
.SH "AUTHORS"
.LP
The GGZ Development Team
<ggz\-dev@mail.ggzgamingzone.org>
.SH "SEE ALSO"
.LP
motd_editor(6)
