.TH "motd_editor" "6" "0.0.12" "The GGZ Development Team" "GGZ Gaming Zone"
.SH "NAME"
.LP
motd_editor \- GNOME tool to design messages of the day (MOTD)
.SH "SYNOPSIS"
.LP
.B motd_editor
.SH "DESCRIPTION"
.LP
GGZ Gaming Zone servers can send a message of the day, either
as an URL to a web page or (more traditionally) a colour-sequence
plain text message.
This tool aids in creating such messages by having the plain
text and its interpretation side by side.
.SH "BUGS"
.LP
This application is currently not well maintained.
.SH "AUTHORS"
.LP
The GGZ Development Team
<ggz\-dev@mail.ggzgamingzone.org>
.SH "SEE ALSO"
.LP
ggz-gnome(6)
