.TH "ggz-gtk" "6" "0.0.8" "The GGZ Development Team" "GGZ Gaming Zone"
.SH "NAME"
.LP
ggz\-gtk \- GTK+ client for GGZ Gaming Zone
.SH "SYNOPSIS"
.LP
\fBggz\-gtk\fR
.SH "DESCRIPTION"
.LP
This is the GTK+ 1.2/2.x client for the GGZ Gaming Zone.  The
program allows a user to connect to a GGZ server and
participate in chat and games.
.LP
Upon launching the program, the user will be presented
with a list of servers they can connect to.  The user can
also type in their own server selections, and add or remove
server profiles.
.LP
For the most part, the program's usage is self\-explanatory.
However, one day, more detailed help will be available
from the help menu within the program.
.SH "FILES"
.LP
.TP
\fB~/.ggz/ggz\-gtk.rc\fR
This file is automatically created and maintained by the
program to store client configuration options.
.SH "BUGS"
.LP
If you encounter any bugs, please contact the GGZ Development
Team.  See our webpage at \fIhttp://www.ggzgamingzone.org\fP
.SH "AUTHORS"
.LP
The GGZ Development Team
<ggz\-dev@mail.ggzgamingzone.org>
.SH "SEE ALSO"
ggz\-config(6)
ggz.modules(5)
