/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"
#include "main.h"
#include "game.h"

GtkWidget *window;

int
main (int argc, char *argv[])
{

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  /*add_pixmap_directory (PACKAGE_DATA_DIR "/pixmaps");*/
  /*add_pixmap_directory (PACKAGE_SOURCE_DIR "/pixmaps");*/

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  window = create_window ();
  gtk_widget_show (window);

  board_init(10, 10);

  gtk_main ();
  return 0;
}

