/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "main_win.h"
#include "support.h"

GtkWidget*
create_main_win (void)
{
  GtkWidget *main_win;
  GtkWidget *vbox1;
  GtkWidget *menubar;
  GtkWidget *file;
  GtkWidget *file_menu;
  GtkAccelGroup *file_menu_accels;
  GtkWidget *exit;
  GtkWidget *hbox1;
  GtkWidget *hpaned1;
  GtkWidget *board;
  GtkWidget *vpaned1;
  GtkWidget *vbox2;
  GtkWidget *white_time;
  GtkWidget *black_time;
  GtkWidget *vbox3;
  GtkWidget *last_moves_label;
  GtkWidget *last_moves;
  GtkWidget *statusbar;

  main_win = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (main_win), "main_win", main_win);
  gtk_window_set_title (GTK_WINDOW (main_win), _("GGZ Chess"));

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (main_win), vbox1);

  menubar = gtk_menu_bar_new ();
  gtk_widget_ref (menubar);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "menubar", menubar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar, FALSE, FALSE, 0);

  file = gtk_menu_item_new_with_label (_("File"));
  gtk_widget_ref (file);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "file", file,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file);
  gtk_container_add (GTK_CONTAINER (menubar), file);

  file_menu = gtk_menu_new ();
  gtk_widget_ref (file_menu);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "file_menu", file_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file), file_menu);
  file_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (file_menu));

  exit = gtk_menu_item_new_with_label (_("Exit"));
  gtk_widget_ref (exit);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "exit", exit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exit);
  gtk_container_add (GTK_CONTAINER (file_menu), exit);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, TRUE, TRUE, 0);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_ref (hpaned1);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "hpaned1", hpaned1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hpaned1);
  gtk_box_pack_start (GTK_BOX (hbox1), hpaned1, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (hpaned1), 0);

  board = gtk_drawing_area_new ();
  gtk_widget_ref (board);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "board", board,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (board);
  gtk_paned_pack1 (GTK_PANED (hpaned1), board, FALSE, FALSE);
  gtk_widget_set_usize (board, 512, 512);
  gtk_widget_set_events (board, GDK_BUTTON_PRESS_MASK);

  vpaned1 = gtk_vpaned_new ();
  gtk_widget_ref (vpaned1);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "vpaned1", vpaned1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vpaned1);
  gtk_paned_pack2 (GTK_PANED (hpaned1), vpaned1, TRUE, TRUE);
  gtk_paned_set_position (GTK_PANED (vpaned1), 0);

  vbox2 = gtk_vbox_new (TRUE, 15);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_paned_pack1 (GTK_PANED (vpaned1), vbox2, FALSE, FALSE);

  white_time = gtk_label_new (_("White -> 99:99"));
  gtk_widget_ref (white_time);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "white_time", white_time,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (white_time);
  gtk_box_pack_start (GTK_BOX (vbox2), white_time, TRUE, TRUE, 0);

  black_time = gtk_label_new (_("Black -> 99:99"));
  gtk_widget_ref (black_time);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "black_time", black_time,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (black_time);
  gtk_box_pack_start (GTK_BOX (vbox2), black_time, TRUE, TRUE, 0);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_paned_pack2 (GTK_PANED (vpaned1), vbox3, FALSE, TRUE);

  last_moves_label = gtk_label_new (_("Last moves"));
  gtk_widget_ref (last_moves_label);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "last_moves_label", last_moves_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (last_moves_label);
  gtk_box_pack_start (GTK_BOX (vbox3), last_moves_label, FALSE, FALSE, 0);

  last_moves = gtk_list_new ();
  gtk_widget_ref (last_moves);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "last_moves", last_moves,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (last_moves);
  gtk_box_pack_start (GTK_BOX (vbox3), last_moves, TRUE, TRUE, 0);
  gtk_widget_set_usize (last_moves, 150, -2);

  statusbar = gtk_statusbar_new ();
  gtk_widget_ref (statusbar);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "statusbar", statusbar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (statusbar);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar, FALSE, FALSE, 0);

  gtk_signal_connect (GTK_OBJECT (exit), "activate",
                      GTK_SIGNAL_FUNC (on_exit_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (board), "configure_event",
                      GTK_SIGNAL_FUNC (on_board_configure_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (board), "expose_event",
                      GTK_SIGNAL_FUNC (on_board_expose_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (board), "button_press_event",
                      GTK_SIGNAL_FUNC (on_board_button_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (board), "drag_drop",
                      GTK_SIGNAL_FUNC (on_board_drag_drop),
                      NULL);

  return main_win;
}

