#!/usr/bin/env python
# Server for the Chinese Chess game
# Copyright (C) 2004 Josef Spillner <josef@ggzgamingzone.org>
# Published under GNU GPL conditions

from Numeric import *
import socket
import sys
import time
import random
import os, pwd
import re

import ggzdmod
from xadrezlib import *

def main():
	global net
	global madeturn
	global surface
	global winner

	""" Setup """

	xadrez = Xadrez()

	""" Main loop """

	madeturn = 0
	againturn = 0
	aierror = 0
	humanerror = 0
	gameover = 0
	winner = 0
	message = ""

	lastpos = (-1, -1)

	move = re.compile("move from (\d+),(\d+) to (\d+),(\d+)")

	while 1:
		line = raw_input(": ")
		m = move.match(line)
		if m:
			x1 = m.group(1)
			y1 = m.group(2)
			x2 = m.group(3)
			y2 = m.group(4)
			# xadrez.validate(x1, y1, x2, y2)

if __name__ == "__main__":
	main()

