#!/usr/bin/env python
# Server for the Chinese Chess game
# Copyright (C) 2004 Josef Spillner <josef@ggzgamingzone.org>
# Published under GNU GPL conditions

from Numeric import *
import socket
import sys
import time
import random
import os, pwd
import re

import ggzdmod
from xadrezlib import *

def hook_state ():
	print "* state"

def hook_join (seat):
	print "* join: ", seat
	print "(Name: " + ggzdmod.getPlayerName(seat) + ")"

def hook_leave (seat):
	print "* leave: ", seat
	print "(Name: " + ggzdmod.getPlayerName(seat) + ")"

def hook_log ():
	print "* log"

def hook_data (seat):
	print "* data: ", seat
	print "(Name: " + ggzdmod.getPlayerName(seat) + ")"

def hook_error (arg):
	print "* error"

def initggz():
	ggzdmod.setHandler(ggzdmod.EVENT_STATE, hook_state)
	ggzdmod.setHandler(ggzdmod.EVENT_JOIN, hook_join)
	ggzdmod.setHandler(ggzdmod.EVENT_LEAVE, hook_leave)
	ggzdmod.setHandler(ggzdmod.EVENT_LOG, hook_log)
	ggzdmod.setHandler(ggzdmod.EVENT_DATA, hook_data)
	ggzdmod.setHandler(ggzdmod.EVENT_ERROR, hook_error)

def main():
	global net
	global madeturn
	global surface
	global winner

	print "### launched"

	""" Setup """

	xadrez = Xadrez()

	print "### go init ggz"

	initggz()

	print "### now go loop"

	ggzdmod.connect()
	ggzdmod.mainLoop()

	""" Main loop """

	madeturn = 0
	againturn = 0
	aierror = 0
	humanerror = 0
	gameover = 0
	winner = 0
	message = ""

	lastpos = (-1, -1)

	move = re.compile("move from (\d+),(\d+) to (\d+),(\d+)")

	while 1:
		line = raw_input(": ")
		m = move.match(line)
		if m:
			x1 = m.group(1)
			y1 = m.group(2)
			x2 = m.group(3)
			y2 = m.group(4)
			# xadrez.validate(x1, y1, x2, y2)

if __name__ == "__main__":
	main()

