.TH "agrue" "6" "0.0.4" "The GGZ Development Team" "GGZ Gaming Zone"
.SH "NAME"
.LP 
agrue \- a GGZ Random User Emulator
.SH "DESCRIPTION"
.LP
This utily is useful for developers and users who want to test the
load on GGZ servers and the handling availability of GGZ core clients.
It emulates a random number of players (configurable) and is a good
start for simulating the real life before actually change something
on production servers.
.SH "AUTHORS"
.LP 
The GGZ Development Team
<ggz\-dev@lists.sourceforge.net>
