.TH "ggz-sql" "1" "0.0.15" "The GGZ Development Team" "GGZ Gaming Zone"
.SH "NAME"
.LP
ggz-sql \- SQL database interface to GGZ
.SH "SYNOPSIS"
.LP
\fBggz-sql\fR
.SH "DESCRIPTION"
.LP
Launches an SQL database client to the GGZ database. \fBggz-sql\fR reads
the configuration file and sets up all connection parameters accordingly,
requiring as little involvement from the user as possible. In particular,
it automatically detects whether PostgreSQL or MySQL is being used.
.SH "SEE ALSO"
.LP
ggz-config(6)
.SH "AUTHORS"
.LP
The GGZ Development Team
<ggz\-dev@mail.ggzgamingzone.org>
