.TH "cmd-client" "1" "0.0.7" "The GGZ Development Team" "GGZ Gaming Zone"
.SH "NAME"
.LP
cmd-client \- Useful GGZ server control tool
.SH "SYNOPSIS"
.LP
cmd-client HOST LOGIN PASSWORD COMMAND OPTIONS...
.SH "DESCRIPTION"
.LP
The current cmd-client is able to broadcast messages to all rooms of a GGZ
server. It is launched straightforward from the command line.
.SH "AUTHORS"
.LP
The GGZ Development Team
<ggz\-dev@lists.sourceforge.net>
