.TH "metaserv" "1" "0.0.10" "The GGZ Development Team" "GGZ Gaming Zone"
.SH "NAME"
.LP
metaserv \- The GGZ Meta Server
.SH "DESCRIPTION"
.LP
This server listens to connections on port 15688, and responds to XML or URI
queries with a list of servers of the requested type.
It should be run by server administrators, for example by inetd or xinetd,
or as a stand-alone daemon to allow updates to the internal database.
.SH "AUTHORS"
.LP
The GGZ Development Team
<ggz\-dev@mail.ggzgamingzone.org>
