.TH "telggz" "1" "0.0.10" "The GGZ Development Team" "GGZ Gaming Zone"
.SH "NAME"
.LP
telggz \- GGZ Telnet Wrapper
.SH "DESCRIPTION"
.LP
This is a very simple line-orientated core client for the GGZ Gaming Zone.
It can be used over telnet connections, which makes it possible to chat in GGZ
rooms from everywhere in the world.
.SH "COMMANDS"
.LP
A list of possible commands can be obtain with the \fI/help\fR command.
.SH "AUTHORS"
.LP
The GGZ Development Team
<ggz\-dev@mail.ggzgamingzone.org>
