#!/usr/bin/env perl

if($ARGV[0]){$f = $ARGV[0];}else{$f = "tmp.po";}
open(F, $f) || die "Cannot open $f";

%props = ();

while(<F>){
	chomp;

	if(/^#\. PROPERTY/){
		$_ =~ s/^#\. PROPERTY//;
		$prop = $_;
	}elsif(/^msgid \"(.*)\"$/){
		$id = $1;
		$f = "id";
	}elsif(/^msgstr \"(.*)\"$/){
		$str = $1;
		$f = "str";
	}elsif(/^\"(.*)\"$/){
		$x = $1;
		if($f eq "id"){
			$id .= $x;
		}else{
			$str .= $x;
		}
	}elsif(/^#/){
		next;
	}elsif($prop ne ""){
		foreach $p(split(/ /, $prop)){
			next if $p eq "";
			$props{$p} = $str;
		}
		$prop = "";
	}
}
close(F);

if($prop ne ""){
	foreach $p(split(/ /, $prop)){
		next if $p eq "";
		$props{$p} = $str;
	}
	$prop = "";
}

print "# AUTOGENERATED via pot2proprev.pl!\n\n";
foreach $p(sort(keys(%props))){
	$str = $props{$p};
	print "$p=$str\n";
}
