TTT_VERSION=0.0.5

TTT_PROTOCOL_ENGINE=TicTacToe
TTT_PROTOCOL_VERSION=5

AC_SUBST(TTT_VERSION)
AC_SUBST(TTT_PROTOCOL_ENGINE)
AC_SUBST(TTT_PROTOCOL_VERSION)

AC_DEFINE_UNQUOTED([TTT_VERSION], "$TTT_VERSION", [TTT version])
AC_DEFINE_UNQUOTED([TTT_PROTOCOL_ENGINE], "$TTT_PROTOCOL_ENGINE",
		   [TTT protocol engine])
AC_DEFINE_UNQUOTED([TTT_PROTOCOL_VERSION], "$TTT_PROTOCOL_VERSION",
		   [TTT protocol version])
