/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include <stdio.h>

#include "support.h"
#include "main.h"
#include "dlg_main.h"
#include "table.h"

GtkWidget *dlg_main = NULL;

int main(int argc, char *argv[])
{
	gtk_init(&argc, &argv);

	dlg_main = create_dlg_main();

	gtk_widget_show(dlg_main);

	table_initialize();

	gtk_main();
	return 0;
}
