extern void table_initialize(void);
extern void table_handle_expose_event(GdkEventExpose *);
extern void table_handle_click_event(GdkEventButton *);
extern void table_set_name(int, char *);
extern void table_display_hand(void);
extern void table_set_bid(int, int);
extern void table_set_tricks(int, int);
extern void table_set_score(int, int);
extern void table_set_trump(void);
extern void table_animation_abort(void);
extern void table_animation_zip(void);
extern void table_animation_opponent(char, char);
extern void table_clear_table(void);
