<div id="main">
	<h1>
		<span class="itemleader">:: </span>
		Welcome to GGZ Community at aKademy 2008!
		<span class="itemleader"> :: </span>
		<a name="extending"></a>
	</h1>
	<div class="text">
		This site is the web frontend to the GGZ server which runs the
		aKademy 2008 game tournaments. Feel free to browse around, but
		ultimately you'll need an account in order to participate in the
		tourney.
	</div>
</div>
