DOTS_VERSION=0.0.4

DOTS_PROTOCOL_ENGINE=Dots
DOTS_PROTOCOL_VERSION=4

AC_SUBST(DOTS_VERSION)
AC_SUBST(DOTS_PROTOCOL_ENGINE)
AC_SUBST(DOTS_PROTOCOL_VERSION)

AC_DEFINE_UNQUOTED([DOTS_VERSION], "$DOTS_VERSION", [Dots version])
AC_DEFINE_UNQUOTED([DOTS_PROTOCOL_ENGINE], "$DOTS_PROTOCOL_ENGINE",
		   [Dots protocol engine])
AC_DEFINE_UNQUOTED([DOTS_PROTOCOL_VERSION], "$DOTS_PROTOCOL_VERSION",
		   [Dots protocol version])
